// words.js - 한국어 어휘 데이터베이스 (중복 없음, 명사만)

const allWords = [
  {
    word: '강아지',
    topic: 'Động vật',
    hint: 'Con chó nhỏ, thú cưng phổ biến',
    koreanExample: '우리 집에는 귀여운 강아지가 한 마리 있어요.',
    vietnameseExample: 'Nhà tôi có một con chó nhỏ dễ thương.',
  },
  {
    word: '고양이',
    topic: 'Động vật',
    hint: 'Con vật nuôi, thường bắt chuột',
    koreanExample: '고양이는 쥐를 잡는 것을 좋아해요.',
    vietnameseExample: 'Mèo thích bắt chuột.',
  },
  {
    word: '토끼',
    topic: 'Động vật',
    hint: 'Con vật có tai dài, thích ăn cà rốt',
    koreanExample: '토끼는 당근을 좋아해요.',
    vietnameseExample: 'Thỏ thích ăn cà rốt.',
  },
  {
    word: '다람쥐',
    topic: 'Động vật',
    hint: 'Con vật nhỏ, sống trên cây, thích ăn hạt',
    koreanExample: '다람쥐는 도토리를 모으고 있어요.',
    vietnameseExample: 'Sóc đang thu thập quả sồi.',
  },
  {
    word: '쥐',
    topic: 'Động vật',
    hint: 'Con vật nhỏ, có đuôi dài',
    koreanExample: '쥐가 치즈를 먹고 있어요.',
    vietnameseExample: 'Chuột đang ăn phô mai.',
  },
  {
    word: '소',
    topic: 'Động vật',
    hint: 'Con vật nuôi lớn, cho sữa',
    koreanExample: '농부는 매일 소에게 먹이를 줍니다.',
    vietnameseExample: 'Người nông dân cho bò ăn mỗi ngày.',
  },
  {
    word: '말',
    topic: 'Động vật',
    hint: 'Con vật lớn, dùng để cưỡi',
    koreanExample: '그는 말을 타고 여행하는 것을 좋아해요.',
    vietnameseExample: 'Anh ấy thích đi du lịch bằng ngựa.',
  },
  {
    word: '양',
    topic: 'Động vật',
    hint: 'Con vật nuôi có lông, cho len',
    koreanExample: '목자는 양을 돌보고 있어요.',
    vietnameseExample: 'Người chăn cừu đang chăm sóc cừu.',
  },
  {
    word: '염소',
    topic: 'Động vật',
    hint: 'Con vật nuôi, có sừng, cho sữa',
    koreanExample: '염소는 풀을 먹고 있어요.',
    vietnameseExample: 'Dê đang ăn cỏ.',
  },
  {
    word: '돼지',
    topic: 'Động vật',
    hint: 'Con vật nuôi, màu hồng',
    koreanExample: '돼지는 진흙 속에서 놀고 있어요.',
    vietnameseExample: 'Lợn đang chơi trong bùn.',
  },
  {
    word: '닭',
    topic: 'Động vật',
    hint: 'Con vật nuôi, đẻ trứng',
    koreanExample: '닭이 알을 낳았어요.',
    vietnameseExample: 'Gà đẻ trứng.',
  },
  {
    word: '오리',
    topic: 'Động vật',
    hint: 'Con vật có chân màng, thích nước',
    koreanExample: '오리가 호수에서 수영하고 있어요.',
    vietnameseExample: 'Vịt đang bơi trong hồ.',
  },
  {
    word: '거위',
    topic: 'Động vật',
    hint: 'Con vật lớn giống vịt, có cổ dài',
    koreanExample: '거위가 공원에서 걷고 있어요.',
    vietnameseExample: 'Ngỗng đang đi bộ trong công viên.',
  },
  {
    word: '사자',
    topic: 'Động vật',
    hint: 'Con vật hoang dã, được gọi là chúa tể rừng xanh',
    koreanExample: '사자는 아프리카에서 주로 볼 수 있어요.',
    vietnameseExample: 'Sư tử chủ yếu có thể thấy ở Châu Phi.',
  },
  {
    word: '호랑이',
    topic: 'Động vật',
    hint: 'Con vật có sọc, rất nguy hiểm',
    koreanExample: '한국 민담에는 호랑이가 자주 등장해요.',
    vietnameseExample: 'Hổ thường xuất hiện trong truyện dân gian Hàn Quốc.',
  },
  {
    word: '표범',
    topic: 'Động vật',
    hint: 'Con vật hoang dã có đốm',
    koreanExample: '표범은 나무에 올라가는 것을 잘해요.',
    vietnameseExample: 'Báo giỏi trèo cây.',
  },
  {
    word: '코끼리',
    topic: 'Động vật',
    hint: 'Con vật lớn nhất trên đất liền, có vòi dài',
    koreanExample: '코끼리는 긴 코를 가지고 있어요.',
    vietnameseExample: 'Voi có chiếc vòi dài.',
  },
  {
    word: '기린',
    topic: 'Động vật',
    hint: 'Con vật có cổ dài',
    koreanExample: '기린은 높은 나뭇잎을 먹을 수 있어요.',
    vietnameseExample: 'Hươu cao cổ có thể ăn lá cây cao.',
  },
  {
    word: '원숭이',
    topic: 'Động vật',
    hint: 'Con vật giống người, thích leo trèo',
    koreanExample: '원숭이가 나무에서 바나나를 먹고 있어요.',
    vietnameseExample: 'Khỉ đang ăn chuối trên cây.',
  },
  {
    word: '하마',
    topic: 'Động vật',
    hint: 'Con vật lớn, sống trong nước và đất liền',
    koreanExample: '하마는 물속에서 많은 시간을 보내요.',
    vietnameseExample: 'Hà mã dành nhiều thời gian trong nước.',
  },
  {
    word: '고래',
    topic: 'Động vật',
    hint: 'Con vật biển lớn nhất',
    koreanExample: '고래는 바다에서 사는 포유류예요.',
    vietnameseExample: 'Cá voi là động vật có vú sống trong biển.',
  },
  {
    word: '상어',
    topic: 'Động vật',
    hint: 'Con vật biển nguy hiểm, có răng sắc',
    koreanExample: '상어는 대양에서 살아요.',
    vietnameseExample: 'Cá mập sống trong đại dương.',
  },
  {
    word: '거북이',
    topic: 'Động vật',
    hint: 'Con vật có mai cứng, di chuyển chậm',
    koreanExample: '거북이는 천천히 걸어요.',
    vietnameseExample: 'Rùa đi bộ chậm chạp.',
  },
  {
    word: '뱀',
    topic: 'Động vật',
    hint: 'Con vật dài, không có chân',
    koreanExample: '뱀은 피부를 주기적으로 벗어요.',
    vietnameseExample: 'Rắn thay da định kỳ.',
  },
  {
    word: '개구리',
    topic: 'Động vật',
    hint: 'Con vật sống cả trong nước và trên cạn, biết nhảy',
    koreanExample: '개구리가 연못에서 개골개골 울고 있어요.',
    vietnameseExample: 'Ếch đang kêu ộp ộp trong ao.',
  },
  {
    word: '물고기',
    topic: 'Động vật',
    hint: 'Con vật sống trong nước, có vây và mang',
    koreanExample: '물고기가 강에서 헤엄치고 있어요.',
    vietnameseExample: 'Cá đang bơi trong sông.',
  },
  {
    word: '새우',
    topic: 'Động vật',
    hint: 'Con vật biển nhỏ, màu đỏ khi nấu chín',
    koreanExample: '새우는 해산물 요리에 자주 사용돼요.',
    vietnameseExample: 'Tôm thường được sử dụng trong các món hải sản.',
  },
  {
    word: '게',
    topic: 'Động vật',
    hint: 'Con vật biển có vỏ cứng và càng',
    koreanExample: '게는 옆으로 걸어요.',
    vietnameseExample: 'Cua đi ngang.',
  },
  {
    word: '나비',
    topic: 'Động vật',
    hint: 'Con vật có cánh đẹp, bay từ hoa này sang hoa khác',
    koreanExample: '나비가 꽃 위에서 날고 있어요.',
    vietnameseExample: 'Bướm đang bay trên hoa.',
  },
  {
    word: '벌',
    topic: 'Động vật',
    hint: 'Con vật nhỏ, làm mật và có thể đốt',
    koreanExample: '벌이 꿀을 모으고 있어요.',
    vietnameseExample: 'Ong đang thu thập mật.',
  },
  {
    word: '학교',
    topic: 'Trường học',
    hint: 'Nơi học sinh đến học tập',
    koreanExample: '나는 매일 학교에 갑니다.',
    vietnameseExample: 'Tôi đi học ở trường mỗi ngày.',
  },
  {
    word: '교실',
    topic: 'Trường học',
    hint: 'Phòng học trong trường',
    koreanExample: '우리 교실은 2층에 있어요.',
    vietnameseExample: 'Lớp học của chúng tôi ở tầng 2.',
  },
  {
    word: '학생',
    topic: 'Trường học',
    hint: 'Người đi học ở trường',
    koreanExample: '그는 열심히 공부하는 학생입니다.',
    vietnameseExample: 'Anh ấy là học sinh chăm chỉ học tập.',
  },
  {
    word: '선생님',
    topic: 'Trường học',
    hint: 'Người dạy học trong trường',
    koreanExample: '김 선생님은 수학을 가르치십니다.',
    vietnameseExample: 'Thầy giáo Kim dạy môn toán.',
  },
  {
    word: '교장',
    topic: 'Trường học',
    hint: 'Người đứng đầu trường học',
    koreanExample: '교장 선생님이 아침 조회에서 연설을 하셨어요.',
    vietnameseExample: 'Hiệu trưởng đã có bài phát biểu trong buổi chào cờ.',
  },
  {
    word: '수업',
    topic: 'Trường học',
    hint: 'Giờ học',
    koreanExample: '오늘 수업은 9시에 시작합니다.',
    vietnameseExample: 'Giờ học hôm nay bắt đầu lúc 9 giờ.',
  },
  {
    word: '시험',
    topic: 'Trường học',
    hint: 'Bài kiểm tra kiến thức',
    koreanExample: '다음 주에 중간 시험이 있어요.',
    vietnameseExample: 'Tuần sau có bài kiểm tra giữa kỳ.',
  },
  {
    word: '숙제',
    topic: 'Trường học',
    hint: 'Bài tập về nhà',
    koreanExample: '어제 숙제를 다 끝냈어요.',
    vietnameseExample: 'Hôm qua tôi đã hoàn thành bài tập về nhà.',
  },
  {
    word: '책상',
    topic: 'Trường học',
    hint: 'Bàn học',
    koreanExample: '책상 위에 책과 연필이 있어요.',
    vietnameseExample: 'Trên bàn học có sách và bút chì.',
  },
  {
    word: '의자',
    topic: 'Trường học',
    hint: 'Ghế ngồi',
    koreanExample: '교실에는 20개의 의자가 있습니다.',
    vietnameseExample: 'Trong lớp học có 20 chiếc ghế.',
  },
  {
    word: '칠판',
    topic: 'Trường học',
    hint: 'Bảng đen trong lớp học',
    koreanExample: '선생님이 칠판에 문제를 썼어요.',
    vietnameseExample: 'Giáo viên đã viết bài tập lên bảng.',
  },
  {
    word: '지우개',
    topic: 'Trường học',
    hint: 'Đồ dùng để xóa chữ viết',
    koreanExample: '지우개로 연필 글씨를 지웠어요.',
    vietnameseExample: 'Tôi đã dùng tẩy để xóa chữ viết bằng bút chì.',
  },
  {
    word: '연필',
    topic: 'Trường học',
    hint: 'Bút chì',
    koreanExample: '시험에는 연필을 사용해야 합니다.',
    vietnameseExample: 'Trong kỳ thi phải sử dụng bút chì.',
  },
  {
    word: '볼펜',
    topic: 'Trường học',
    hint: 'Bút bi',
    koreanExample: '파란색 볼펜으로 글을 써주세요.',
    vietnameseExample: 'Hãy viết bằng bút bi màu xanh.',
  },
  {
    word: '도서관',
    topic: 'Trường học',
    hint: 'Nơi đọc và mượn sách trong trường',
    koreanExample: '방과 후에 도서관에서 책을 읽었어요.',
    vietnameseExample: 'Sau giờ học tôi đã đọc sách ở thư viện.',
  },
  {
    word: '급식',
    topic: 'Trường học',
    hint: 'Bữa ăn ở trường',
    koreanExample: '오늘 급식은 비빔밥입니다.',
    vietnameseExample: 'Bữa ăn ở trường hôm nay là bibimbap.',
  },
  {
    word: '체육관',
    topic: 'Trường học',
    hint: 'Nơi tập thể dục trong trường',
    koreanExample: '비가 와서 체육 수업은 체육관에서 했어요.',
    vietnameseExample:
      'Vì trời mưa nên giờ thể dục được tổ chức trong nhà thi đấu.',
  },
  {
    word: '운동장',
    topic: 'Trường học',
    hint: 'Sân chơi ngoài trời ở trường',
    koreanExample: '학생들이 운동장에서 축구를 하고 있어요.',
    vietnameseExample: 'Học sinh đang chơi bóng đá ở sân trường.',
  },
  {
    word: '성적',
    topic: 'Trường học',
    hint: 'Điểm số học tập',
    koreanExample: '이번 학기에 성적이 많이 올랐어요.',
    vietnameseExample: 'Học kỳ này điểm số của tôi đã tăng nhiều.',
  },
  {
    word: '졸업',
    topic: 'Trường học',
    hint: 'Hoàn thành khóa học và rời trường',
    koreanExample: '내년에 대학교를 졸업할 예정이에요.',
    vietnameseExample: 'Năm sau tôi dự định tốt nghiệp đại học.',
  },
  {
    word: '입학',
    topic: 'Trường học',
    hint: 'Bắt đầu vào học ở trường mới',
    koreanExample: '3월에 대학교에 입학했어요.',
    vietnameseExample: 'Tôi đã nhập học đại học vào tháng 3.',
  },
  {
    word: '교과서',
    topic: 'Trường học',
    hint: 'Sách học ở trường',
    koreanExample: '새 학기에 새 교과서를 받았어요.',
    vietnameseExample: 'Học kỳ mới tôi đã nhận được sách giáo khoa mới.',
  },
  {
    word: '공책',
    topic: 'Trường học',
    hint: 'Vở ghi chép',
    koreanExample: '수업 시간에 공책에 필기를 했어요.',
    vietnameseExample: 'Trong giờ học tôi đã ghi chép vào vở.',
  },
  {
    word: '수학',
    topic: 'Trường học',
    hint: 'Môn học về con số',
    koreanExample: '수학은 제가 가장 좋아하는 과목이에요.',
    vietnameseExample: 'Toán học là môn học yêu thích nhất của tôi.',
  },
  {
    word: '과학',
    topic: 'Trường học',
    hint: 'Môn học về tự nhiên',
    koreanExample: '오늘 과학 시간에 실험을 했어요.',
    vietnameseExample:
      'Hôm nay trong giờ khoa học chúng tôi đã làm thí nghiệm.',
  },
  {
    word: '역사',
    topic: 'Trường học',
    hint: 'Môn học về quá khứ',
    koreanExample: '역사 시간에 한국 전통에 대해 배웠어요.',
    vietnameseExample:
      'Trong giờ lịch sử chúng tôi đã học về truyền thống Hàn Quốc.',
  },
  {
    word: '방학',
    topic: 'Trường học',
    hint: 'Kỳ nghỉ của trường học',
    koreanExample: '여름 방학에 여행을 갈 거예요.',
    vietnameseExample: 'Tôi sẽ đi du lịch trong kỳ nghỉ hè.',
  },
  {
    word: '등교',
    topic: 'Trường học',
    hint: 'Đi đến trường',
    koreanExample: '매일 아침 8시에 등교합니다.',
    vietnameseExample: 'Mỗi sáng tôi đến trường lúc 8 giờ.',
  },
  {
    word: '하교',
    topic: 'Trường học',
    hint: 'Rời khỏi trường để về nhà',
    koreanExample: '오후 3시에 하교합니다.',
    vietnameseExample: 'Tôi tan học lúc 3 giờ chiều.',
  },
  {
    word: '교복',
    topic: 'Trường học',
    hint: 'Đồng phục học sinh',
    koreanExample: '한국 학생들은 교복을 입고 학교에 갑니다.',
    vietnameseExample: 'Học sinh Hàn Quốc mặc đồng phục đến trường.',
  },
  {
    word: '서울',
    topic: 'Địa danh Hàn Quốc',
    hint: 'Thủ đô của Hàn Quốc',
    koreanExample: '서울은 한국의 수도이자 가장 큰 도시입니다.',
    vietnameseExample: 'Seoul là thủ đô và thành phố lớn nhất của Hàn Quốc.',
  },
  {
    word: '부산',
    topic: 'Địa danh Hàn Quốc',
    hint: 'Thành phố cảng lớn thứ hai của Hàn Quốc',
    koreanExample:
      '부산은 한국에서 두 번째로 큰 도시이자 유명한 항구 도시입니다.',
    vietnameseExample:
      'Busan là thành phố lớn thứ hai và là thành phố cảng nổi tiếng của Hàn Quốc.',
  },
  {
    word: '인천',
    topic: 'Địa danh Hàn Quốc',
    hint: 'Thành phố có sân bay quốc tế lớn của Hàn Quốc',
    koreanExample: '인천국제공항은 한국의 관문입니다.',
    vietnameseExample: 'Sân bay quốc tế Incheon là cửa ngõ của Hàn Quốc.',
  },
  {
    word: '대구',
    topic: 'Địa danh Hàn Quốc',
    hint: 'Thành phố lớn ở miền đông nam Hàn Quốc',
    koreanExample: '대구는 경상북도의 중심 도시입니다.',
    vietnameseExample:
      'Daegu là thành phố trung tâm của tỉnh Gyeongsangbuk-do.',
  },
  {
    word: '광주',
    topic: 'Địa danh Hàn Quốc',
    hint: 'Thành phố lớn ở miền tây nam Hàn Quốc',
    koreanExample: '광주는 호남 지방의 중심 도시입니다.',
    vietnameseExample: 'Gwangju là thành phố trung tâm của vùng Honam.',
  },
  {
    word: '대전',
    topic: 'Địa danh Hàn Quốc',
    hint: 'Thành phố ở trung tâm Hàn Quốc, nổi tiếng về khoa học và công nghệ',
    koreanExample: '대전은 한국의 과학 기술의 중심지입니다.',
    vietnameseExample: 'Daejeon là trung tâm khoa học công nghệ của Hàn Quốc.',
  },
  {
    word: '제주도',
    topic: 'Địa danh Hàn Quốc',
    hint: 'Hòn đảo du lịch nổi tiếng ở phía nam Hàn Quốc',
    koreanExample: '제주도는 한국에서 가장 큰 섬이자 인기 있는 관광지입니다.',
    vietnameseExample:
      'Đảo Jeju là hòn đảo lớn nhất và là điểm du lịch phổ biến ở Hàn Quốc.',
  },
  {
    word: '경주',
    topic: 'Địa danh Hàn Quốc',
    hint: 'Thành phố lịch sử, thủ đô cũ của triều đại Silla',
    koreanExample: '경주에는 많은 역사적인 유적지가 있습니다.',
    vietnameseExample: 'Gyeongju có nhiều di tích lịch sử.',
  },
  {
    word: '설악산',
    topic: 'Địa danh Hàn Quốc',
    hint: 'Ngọn núi nổi tiếng ở phía đông bắc Hàn Quốc',
    koreanExample: '설악산은 한국에서 가장 아름다운 산 중 하나입니다.',
    vietnameseExample:
      'Núi Seoraksan là một trong những ngọn núi đẹp nhất ở Hàn Quốc.',
  },
  {
    word: '한라산',
    topic: 'Địa danh Hàn Quốc',
    hint: 'Núi cao nhất ở Hàn Quốc, nằm ở đảo Jeju',
    koreanExample: '한라산은 제주도의 중앙에 위치한 화산입니다.',
    vietnameseExample: 'Núi Hallasan là núi lửa nằm ở trung tâm đảo Jeju.',
  },
  {
    word: '독도',
    topic: 'Địa danh Hàn Quốc',
    hint: 'Quần đảo ở phía đông Hàn Quốc',
    koreanExample: '독도는 한국의 동쪽 끝에 있는 섬입니다.',
    vietnameseExample: 'Dokdo là hòn đảo nằm ở cực đông của Hàn Quốc.',
  },
  {
    word: '한강',
    topic: 'Địa danh Hàn Quốc',
    hint: 'Dòng sông chảy qua Seoul',
    koreanExample: '한강은 서울을 가로지르는 큰 강입니다.',
    vietnameseExample: 'Sông Hàn là con sông lớn chảy qua Seoul.',
  },
  {
    word: '남산',
    topic: 'Địa danh Hàn Quốc',
    hint: 'Núi nổi tiếng ở trung tâm Seoul',
    koreanExample: '남산 타워에서 서울의 전경을 볼 수 있습니다.',
    vietnameseExample: 'Bạn có thể nhìn toàn cảnh Seoul từ tháp Namsan.',
  },
  {
    word: '명동',
    topic: 'Địa danh Hàn Quốc',
    hint: 'Khu mua sắm nổi tiếng ở Seoul',
    koreanExample: '명동은 서울의 유명한 쇼핑 거리입니다.',
    vietnameseExample: 'Myeongdong là khu phố mua sắm nổi tiếng ở Seoul.',
  },
  {
    word: '강남',
    topic: 'Địa danh Hàn Quốc',
    hint: 'Khu vực giàu có ở phía nam Seoul',
    koreanExample: '강남은 서울의 현대적이고 부유한 지역입니다.',
    vietnameseExample: 'Gangnam là khu vực hiện đại và giàu có ở Seoul.',
  },
  {
    word: '전주',
    topic: 'Địa danh Hàn Quốc',
    hint: 'Thành phố nổi tiếng với văn hóa truyền thống và ẩm thực',
    koreanExample: '전주는 한옥 마을로 유명합니다.',
    vietnameseExample: 'Jeonju nổi tiếng với làng nhà truyền thống Hanok.',
  },
  {
    word: '속초',
    topic: 'Địa danh Hàn Quốc',
    hint: 'Thành phố biển ở bờ đông Hàn Quốc',
    koreanExample: '속초는 아름다운 해변이 있는 동해안 도시입니다.',
    vietnameseExample:
      'Sokcho là thành phố ven biển đông với những bãi biển đẹp.',
  },
  {
    word: '안동',
    topic: 'Địa danh Hàn Quốc',
    hint: 'Thành phố nổi tiếng với văn hóa truyền thống Hàn Quốc',
    koreanExample: '안동은 전통 문화가 잘 보존된 도시입니다.',
    vietnameseExample:
      'Andong là thành phố nơi văn hóa truyền thống được bảo tồn tốt.',
  },
  {
    word: '수원',
    topic: 'Địa danh Hàn Quốc',
    hint: 'Thành phố lớn ở tỉnh Gyeonggi, nổi tiếng với pháo đài Hwaseong',
    koreanExample: '수원 화성은 유네스코 세계문화유산입니다.',
    vietnameseExample:
      'Pháo đài Hwaseong ở Suwon là di sản văn hóa thế giới UNESCO.',
  },
  {
    word: '울산',
    topic: 'Địa danh Hàn Quốc',
    hint: 'Thành phố công nghiệp ở phía đông nam Hàn Quốc',
    koreanExample: '울산은 한국의 중요한 산업 도시입니다.',
    vietnameseExample:
      'Ulsan là thành phố công nghiệp quan trọng của Hàn Quốc.',
  },
  {
    word: '오징어게임',
    topic: 'Phim truyền hình Hàn Quốc',
    hint: 'Bộ phim Netflix nổi tiếng toàn cầu về trò chơi sinh tồn',
    koreanExample: '오징어게임은 전 세계적으로 큰 인기를 끌었습니다.',
    vietnameseExample:
      'Trò chơi con mực đã thu hút sự nổi tiếng trên toàn thế giới.',
  },
  {
    word: '겨울연가',
    topic: 'Phim truyền hình Hàn Quốc',
    hint: 'Bộ phim tình cảm kinh điển làm nên làn sóng Hallyu đầu tiên',
    koreanExample: '겨울연가는 한류의 시작을 알린 드라마입니다.',
    vietnameseExample:
      'Bản tình ca mùa đông là bộ phim báo hiệu sự khởi đầu của làn sóng Hallyu.',
  },
  {
    word: '대장금',
    topic: 'Phim truyền hình Hàn Quốc',
    hint: 'Bộ phim cổ trang về nữ đầu bếp hoàng cung',
    koreanExample: '대장금은 한국 전통 요리를 소개한 역사 드라마입니다.',
    vietnameseExample:
      'Nàng Dae Jang Geum là bộ phim lịch sử giới thiệu ẩm thực truyền thống Hàn Quốc.',
  },
  {
    word: '태양의후예',
    topic: 'Phim truyền hình Hàn Quốc',
    hint: 'Bộ phim về tình yêu giữa bác sĩ và quân nhân',
    koreanExample: '태양의후예는 아시아 전역에서 인기를 끌었습니다.',
    vietnameseExample: 'Hậu duệ mặt trời đã thu hút sự nổi tiếng khắp châu Á.',
  },
  {
    word: '사랑의불시착',
    topic: 'Phim truyền hình Hàn Quốc',
    hint: 'Bộ phim về tình yêu giữa nữ thừa kế Hàn Quốc và sĩ quan Bắc Triều Tiên',
    koreanExample: '사랑의불시착은 현빈과 손예진이 주연한 드라마입니다.',
    vietnameseExample:
      'Hạ cánh nơi anh là bộ phim có sự tham gia của Hyun Bin và Son Ye Jin.',
  },
  {
    word: '도깨비',
    topic: 'Phim truyền hình Hàn Quốc',
    hint: 'Bộ phim về người bảo vệ linh hồn bất tử và cô dâu của anh ta',
    koreanExample:
      '도깨비는 공유와 김고은이 출연한 판타지 로맨스 드라마입니다.',
    vietnameseExample:
      'Yêu tinh là bộ phim tình cảm giả tưởng có sự tham gia của Gong Yoo và Kim Go Eun.',
  },
  {
    word: '미남이시네요',
    topic: 'Phim truyền hình Hàn Quốc',
    hint: 'Bộ phim về cô gái giả trai để gia nhập nhóm nhạc nam',
    koreanExample: '미남이시네요는 여장 남자 밴드에 관한 코미디 드라마입니다.',
    vietnameseExample:
      'Chàng đẹp trai là bộ phim hài về một ban nhạc nam với thành viên nữ cải trang.',
  },
  {
    word: '별에서온그대',
    topic: 'Phim truyền hình Hàn Quốc',
    hint: 'Bộ phim về người ngoài hành tinh sống trên Trái Đất trong 400 năm',
    koreanExample: '별에서온그대는 김수현과 전지현이 주연한 드라마입니다.',
    vietnameseExample:
      'Vì sao đưa anh tới là bộ phim có sự tham gia của Kim Soo Hyun và Jun Ji Hyun.',
  },
  {
    word: '응답하라1988',
    topic: 'Phim truyền hình Hàn Quốc',
    hint: 'Bộ phim hoài niệm về cuộc sống ở Seoul năm 1988',
    koreanExample: '응답하라1988은 청춘과 가족애를 그린 드라마입니다.',
    vietnameseExample:
      'Reply 1988 là bộ phim miêu tả tuổi trẻ và tình yêu gia đình.',
  },
  {
    word: '더킹',
    topic: 'Phim truyền hình Hàn Quốc',
    hint: 'Bộ phim về các vũ trụ song song và tình yêu vượt thời gian',
    koreanExample: '더킹: 영원의 군주는 이민호가 주연한 판타지 드라마입니다.',
    vietnameseExample:
      'Quân vương bất diệt là bộ phim giả tưởng có sự tham gia của Lee Min Ho.',
  },
  {
    word: '스타트업',
    topic: 'Phim truyền hình Hàn Quốc',
    hint: 'Bộ phim về khởi nghiệp công nghệ ở Hàn Quốc',
    koreanExample: '스타트업은 IT 창업을 배경으로 한 로맨스 드라마입니다.',
    vietnameseExample:
      'Start-up là bộ phim tình cảm lấy bối cảnh khởi nghiệp công nghệ thông tin.',
  },
  {
    word: '이태원클라쓰',
    topic: 'Phim truyền hình Hàn Quốc',
    hint: 'Bộ phim về cuộc sống ở khu phố Itaewon và tình bạn',
    koreanExample: '이태원클라쓰는 사업가 이야기를 다룬 드라마입니다.',
    vietnameseExample:
      'Itaewon Class là bộ phim kể về câu chuyện của một doanh nhân.',
  },
  {
    word: '동백꽃필무렵',
    topic: 'Phim truyền hình Hàn Quốc',
    hint: 'Bộ phim lãng mạn ở thị trấn ven biển nhỏ',
    koreanExample: '동백꽃필무렵은 따뜻한 감성의 로맨스 드라마입니다.',
    vietnameseExample: 'Khi hoa trà nở là bộ phim tình cảm ấm áp.',
  },
  {
    word: '김비서가왜그럴까',
    topic: 'Phim truyền hình Hàn Quốc',
    hint: 'Bộ phim về mối quan hệ giữa sếp và thư ký',
    koreanExample: '김비서가왜그럴까는 직장 로맨스 코미디입니다.',
    vietnameseExample:
      'Thư ký Kim sao thế? là bộ phim hài tình cảm về công sở.',
  },
  {
    word: '비밀의숲',
    topic: 'Phim truyền hình Hàn Quốc',
    hint: 'Bộ phim trinh thám về công tố viên không có cảm xúc',
    koreanExample: '비밀의숲은 복잡한 추리와 정치 음모를 다룬 드라마입니다.',
    vietnameseExample:
      'Khu rừng bí mật là bộ phim về những vụ án phức tạp và âm mưu chính trị.',
  },
  {
    word: '육십일',
    topic: 'Phim truyền hình Hàn Quốc',
    hint: 'Bộ phim về cuộc chiến tranh Triều Tiên và tình yêu',
    koreanExample: '육십일은 한국전쟁을 배경으로 한 역사 드라마입니다.',
    vietnameseExample:
      'Hậu duệ của mặt trời là bộ phim lịch sử lấy bối cảnh chiến tranh Triều Tiên.',
  },
  {
    word: '구르미그린달빛',
    topic: 'Phim truyền hình Hàn Quốc',
    hint: 'Bộ phim cổ trang về hoàng tử và cô gái cải trang thành quan chức',
    koreanExample:
      '구르미그린달빛은 조선 시대를 배경으로 한 로맨스 사극입니다.',
    vietnameseExample:
      'Mây họa ánh trăng là bộ phim cổ trang lãng mạn lấy bối cảnh thời Joseon.',
  },
  {
    word: '옥탑방고양이',
    topic: 'Phim truyền hình Hàn Quốc',
    hint: 'Bộ phim cổ điển về cô gái sống ở căn phòng áp mái',
    koreanExample: '옥탑방고양이는 2000년대 초반의 인기 드라마였습니다.',
    vietnameseExample:
      'Chuyện tình nàng Mèo là bộ phim nổi tiếng đầu những năm 2000.',
  },
  {
    word: '신사의품격',
    topic: 'Phim truyền hình Hàn Quốc',
    hint: 'Bộ phim về tình bạn và tình yêu của bốn người đàn ông tuổi 40',
    koreanExample:
      '신사의품격은 네 명의 중년 남성의 우정과 사랑을 그린 드라마입니다.',
    vietnameseExample:
      'Phẩm cách quý ông là bộ phim miêu tả tình bạn và tình yêu của bốn người đàn ông trung niên.',
  },
  {
    word: '방탄소년단',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: 'Nhóm nhạc K-pop nổi tiếng toàn cầu, còn gọi là BTS',
    koreanExample: '방탄소년단은 빌보드 차트에서 1위를 했습니다.',
    vietnameseExample: 'BTS đã đứng đầu bảng xếp hạng Billboard.',
  },
  {
    word: '손흥민',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: 'Cầu thủ bóng đá nổi tiếng, chơi cho Tottenham Hotspur',
    koreanExample: '손흥민은 프리미어 리그에서 활약하는 축구 선수입니다.',
    vietnameseExample:
      'Son Heung-min là cầu thủ bóng đá thi đấu tại Premier League.',
  },
  {
    word: '김연아',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: 'Vận động viên trượt băng nghệ thuật nổi tiếng',
    koreanExample: '김연아는 피겨 스케이팅 올림픽 금메달리스트입니다.',
    vietnameseExample:
      'Kim Yuna là vận động viên đoạt huy chương vàng Olympic môn trượt băng nghệ thuật.',
  },
  {
    word: '이병헌',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: 'Nam diễn viên nổi tiếng trong phim Hàn Quốc và Hollywood',
    koreanExample: '이병헌은 국내외에서 인정받는 배우입니다.',
    vietnameseExample:
      'Lee Byung-hun là diễn viên được công nhận cả trong nước và quốc tế.',
  },
  {
    word: '전지현',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: "Nữ diễn viên nổi tiếng, đóng phim 'Vì sao đưa anh tới'",
    koreanExample: '전지현은 별에서 온 그대에서 주연을 맡았습니다.',
    vietnameseExample:
      'Jun Ji-hyun đã đóng vai chính trong phim Vì sao đưa anh tới.',
  },
  {
    word: '봉준호',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: 'Đạo diễn nổi tiếng, đạo diễn phim Ký sinh trùng',
    koreanExample: "봉준호 감독은 영화 '기생충'으로 아카데미상을 받았습니다.",
    vietnameseExample:
      "Đạo diễn Bong Joon-ho đã nhận giải Oscar cho bộ phim 'Parasite'.",
  },
  {
    word: '블랙핑크',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: 'Nhóm nhạc nữ K-pop nổi tiếng toàn cầu',
    koreanExample: '블랙핑크는 전 세계적으로 인기 있는 걸그룹입니다.',
    vietnameseExample:
      'Blackpink là nhóm nhạc nữ được yêu thích trên toàn thế giới.',
  },
  {
    word: '싸이',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: "Ca sĩ nổi tiếng với bài hát 'Gangnam Style'",
    koreanExample: '싸이의 강남스타일은 유튜브에서 큰 인기를 끌었습니다.',
    vietnameseExample:
      'Bài hát Gangnam Style của PSY đã trở nên rất phổ biến trên YouTube.',
  },
  {
    word: '김수현',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: "Nam diễn viên nổi tiếng, đóng phim 'Vì sao đưa anh tới'",
    koreanExample: '김수현은 별에서 온 그대에서 도민준 역할을 맡았습니다.',
    vietnameseExample:
      'Kim Soo-hyun đã đóng vai Do Min-joon trong phim Vì sao đưa anh tới.',
  },
  {
    word: '세종대왕',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: 'Vị vua nổi tiếng, người sáng tạo ra chữ Hàn Quốc (Hangul)',
    koreanExample: '세종대왕은 한글을 창제한 조선의 왕입니다.',
    vietnameseExample:
      'Vua Sejong Đại đế là vị vua triều Joseon đã sáng tạo ra chữ Hàn Quốc.',
  },
  {
    word: '김치',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: 'Người có tác phẩm nhiều hơn chồng',
    koreanExample: '김치를 만드는 과정은 복잡합니다.',
    vietnameseExample: 'The process of making kimchi is complex.',
  },
  {
    word: '이민호',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: "Nam diễn viên nổi tiếng, đóng phim 'Những người thừa kế'",
    koreanExample: '이민호는 상속자들에서 김탄 역할로 유명해졌습니다.',
    vietnameseExample:
      'Lee Min-ho nổi tiếng với vai Kim Tan trong phim Những người thừa kế.',
  },
  {
    word: '손예진',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: "Nữ diễn viên nổi tiếng, đóng phim 'Hạ cánh nơi anh'",
    koreanExample: '손예진은 사랑의 불시착에서 윤세리 역할을 맡았습니다.',
    vietnameseExample:
      'Son Ye-jin đã đóng vai Yoon Se-ri trong phim Hạ cánh nơi anh.',
  },
  {
    word: '현빈',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: "Nam diễn viên nổi tiếng, đóng phim 'Hạ cánh nơi anh'",
    koreanExample: '현빈은 사랑의 불시착에서 리정혁 역할을 맡았습니다.',
    vietnameseExample:
      'Hyun Bin đã đóng vai Ri Jung-hyuk trong phim Hạ cánh nơi anh.',
  },
  {
    word: '박찬호',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: 'Cầu thủ bóng chày nổi tiếng, từng thi đấu tại MLB',
    koreanExample: '박찬호는 메이저 리그에서 활약한 야구 선수입니다.',
    vietnameseExample:
      'Park Chan-ho là cầu thủ bóng chày từng thi đấu tại Giải bóng chày Mỹ (MLB).',
  },
  {
    word: '윤여정',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: 'Nữ diễn viên kỳ cựu, từng đoạt giải Oscar',
    koreanExample: "윤여정은 영화 '미나리'로 아카데미상을 받았습니다.",
    vietnameseExample: "Youn Yuh-jung đã nhận giải Oscar cho bộ phim 'Minari'.",
  },
  {
    word: '박서준',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: "Nam diễn viên nổi tiếng, đóng phim 'Itaewon Class'",
    koreanExample: '박서준은 이태원 클라쓰에서 주연을 맡았습니다.',
    vietnameseExample:
      'Park Seo-joon đã đóng vai chính trong phim Itaewon Class.',
  },
  {
    word: '아이유',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: 'Nữ ca sĩ và diễn viên nổi tiếng',
    koreanExample: '아이유는 가수이자 배우로 활동하고 있습니다.',
    vietnameseExample: 'IU hoạt động với tư cách là ca sĩ và diễn viên.',
  },
  {
    word: '공유',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: "Nam diễn viên nổi tiếng, đóng phim 'Yêu tinh'",
    koreanExample: '공유는 도깨비에서 김신 역할을 맡았습니다.',
    vietnameseExample: 'Gong Yoo đã đóng vai Kim Shin trong phim Yêu tinh.',
  },
  {
    word: '조용필',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: "Ca sĩ kỳ cựu, được gọi là 'Hoàng tử nhạc pop'",
    koreanExample: '조용필은 한국의 국민 가수입니다.',
    vietnameseExample: 'Cho Yong-pil là ca sĩ quốc dân của Hàn Quốc.',
  },
  {
    word: '한소희',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: "Nữ diễn viên trẻ nổi tiếng, đóng phim 'Nevertheless'",
    koreanExample: '한소희는 그럼에도 불구하고에서 유나비 역할을 맡았습니다.',
    vietnameseExample:
      'Han So-hee đã đóng vai Yoo Na-bi trong phim Nevertheless.',
  },
  {
    word: '이상화',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: 'Vận động viên trượt băng tốc độ nổi tiếng',
    koreanExample: '이상화는 스피드 스케이팅 올림픽 금메달리스트입니다.',
    vietnameseExample:
      'Lee Sang-hwa là vận động viên đoạt huy chương vàng Olympic môn trượt băng tốc độ.',
  },
  {
    word: '송강호',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: "Nam diễn viên nổi tiếng, đóng phim 'Ký sinh trùng'",
    koreanExample: '송강호는 기생충에서 김기택 역할을 맡았습니다.',
    vietnameseExample:
      'Song Kang-ho đã đóng vai Kim Ki-taek trong phim Ký sinh trùng.',
  },
  {
    word: '제이홉',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: 'Thành viên của nhóm nhạc BTS',
    koreanExample: '제이홉은 방탄소년단의 멤버입니다.',
    vietnameseExample: 'J-Hope là thành viên của nhóm nhạc BTS.',
  },
  {
    word: '백종원',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: 'Đầu bếp nổi tiếng và doanh nhân',
    koreanExample: '백종원은 유명한 요리사이자 사업가입니다.',
    vietnameseExample: 'Baek Jong-won là đầu bếp nổi tiếng và doanh nhân.',
  },
  {
    word: '유재석',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: 'MC và nghệ sĩ hài nổi tiếng',
    koreanExample: '유재석은 한국에서 가장 인기 있는 MC 중 한 명입니다.',
    vietnameseExample:
      'Yoo Jae-suk là một trong những MC được yêu thích nhất ở Hàn Quốc.',
  },
  {
    word: '안성기',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: 'Nam diễn viên kỳ cựu trong điện ảnh Hàn Quốc',
    koreanExample: '안성기는 한국 영화계의 대표적인 배우입니다.',
    vietnameseExample:
      'Ahn Sung-ki là diễn viên tiêu biểu của nền điện ảnh Hàn Quốc.',
  },
  {
    word: '이영애',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: "Nữ diễn viên nổi tiếng, đóng phim 'Nàng Dae Jang Geum'",
    koreanExample: '이영애는 대장금에서 주연을 맡았습니다.',
    vietnameseExample:
      'Lee Young-ae đã đóng vai chính trong phim Nàng Dae Jang Geum.',
  },
  {
    word: '이건희',
    topic: 'Người nổi tiếng Hàn Quốc',
    hint: 'Cố Chủ tịch tập đoàn Samsung',
    koreanExample: '이건희는 삼성그룹을 세계적인 기업으로 성장시켰습니다.',
    vietnameseExample:
      'Lee Kun-hee đã phát triển Tập đoàn Samsung thành công ty toàn cầu.',
  },
  {
    word: '하노이',
    topic: 'Địa danh Việt Nam',
    hint: 'Thủ đô của Việt Nam',
    koreanExample: '하노이는 베트남의 수도입니다.',
    vietnameseExample: 'Hà Nội là thủ đô của Việt Nam.',
  },
  {
    word: '호찌민',
    topic: 'Địa danh Việt Nam',
    hint: 'Thành phố lớn nhất Việt Nam, trước đây có tên là Sài Gòn',
    koreanExample: '호찌민시는 베트남에서 가장 큰 도시입니다.',
    vietnameseExample: 'Thành phố Hồ Chí Minh là thành phố lớn nhất Việt Nam.',
  },
  {
    word: '다낭',
    topic: 'Địa danh Việt Nam',
    hint: 'Thành phố biển ở miền Trung Việt Nam',
    koreanExample: '다낭은 아름다운 해변으로 유명한 도시입니다.',
    vietnameseExample: 'Đà Nẵng là thành phố nổi tiếng với những bãi biển đẹp.',
  },
  {
    word: '하롱베이',
    topic: 'Địa danh Việt Nam',
    hint: 'Vịnh đẹp ở miền Bắc Việt Nam, di sản thế giới UNESCO',
    koreanExample: '하롱베이는 유네스코 세계자연유산입니다.',
    vietnameseExample:
      'Vịnh Hạ Long là di sản thiên nhiên thế giới của UNESCO.',
  },
  {
    word: '호이안',
    topic: 'Địa danh Việt Nam',
    hint: 'Phố cổ ở miền Trung Việt Nam, di sản thế giới UNESCO',
    koreanExample: '호이안은 잘 보존된 고대 무역 항구입니다.',
    vietnameseExample: 'Hội An là cảng thương mại cổ được bảo tồn tốt.',
  },
  {
    word: '후에',
    topic: 'Địa danh Việt Nam',
    hint: 'Cố đô của Việt Nam, nơi có nhiều di tích lịch sử',
    koreanExample: '후에는 베트남의 옛 수도였습니다.',
    vietnameseExample: 'Huế từng là cố đô của Việt Nam.',
  },
  {
    word: '사파',
    topic: 'Địa danh Việt Nam',
    hint: 'Thị trấn vùng cao ở miền Bắc Việt Nam, nổi tiếng với ruộng bậc thang',
    koreanExample: '사파는 아름다운 계단식 논으로 유명합니다.',
    vietnameseExample: 'Sa Pa nổi tiếng với những thửa ruộng bậc thang đẹp.',
  },
  {
    word: '나트랑',
    topic: 'Địa danh Việt Nam',
    hint: 'Thành phố biển xinh đẹp ở miền Trung Việt Nam',
    koreanExample: '나트랑은 아름다운 해변 휴양지입니다.',
    vietnameseExample: 'Nha Trang là khu nghỉ dưỡng biển đẹp.',
  },
  {
    word: '달랏',
    topic: 'Địa danh Việt Nam',
    hint: 'Thành phố trên cao nguyên, được gọi là thành phố của những loài hoa',
    koreanExample: "달랏은 '꽃의 도시'라고 불립니다.",
    vietnameseExample: "Đà Lạt được gọi là 'thành phố của những loài hoa'.",
  },
  {
    word: '선생님',
    topic: 'Nghề nghiệp',
    hint: 'Người dạy học tại trường',
    koreanExample: '제 꿈은 선생님이 되는 것입니다.',
    vietnameseExample: 'Ước mơ của tôi là trở thành giáo viên.',
  },
  {
    word: '의사',
    topic: 'Nghề nghiệp',
    hint: 'Người khám và chữa bệnh',
    koreanExample: '그는 유명한 의사입니다.',
    vietnameseExample: 'Anh ấy là một bác sĩ nổi tiếng.',
  },
  {
    word: '간호사',
    topic: 'Nghề nghiệp',
    hint: 'Người chăm sóc bệnh nhân tại bệnh viện',
    koreanExample: '간호사는 환자를 돌봅니다.',
    vietnameseExample: 'Y tá chăm sóc bệnh nhân.',
  },
  {
    word: '요리사',
    topic: 'Nghề nghiệp',
    hint: 'Người nấu ăn chuyên nghiệp',
    koreanExample: '그녀는 유명한 레스토랑의 요리사입니다.',
    vietnameseExample: 'Cô ấy là đầu bếp của một nhà hàng nổi tiếng.',
  },
  {
    word: '경찰',
    topic: 'Nghề nghiệp',
    hint: 'Người bảo vệ an ninh trật tự',
    koreanExample: '경찰은 시민의 안전을 지킵니다.',
    vietnameseExample: 'Cảnh sát bảo vệ an toàn cho người dân.',
  },
  {
    word: '소방관',
    topic: 'Nghề nghiệp',
    hint: 'Người chữa cháy',
    koreanExample: '소방관은 화재를 진압합니다.',
    vietnameseExample: 'Lính cứu hỏa dập tắt đám cháy.',
  },
  {
    word: '변호사',
    topic: 'Nghề nghiệp',
    hint: 'Người hành nghề luật',
    koreanExample: '그는 유능한 변호사입니다.',
    vietnameseExample: 'Anh ấy là luật sư giỏi.',
  },
  {
    word: '공무원',
    topic: 'Nghề nghiệp',
    hint: 'Người làm việc cho chính phủ',
    koreanExample: '그녀는 공무원 시험에 합격했습니다.',
    vietnameseExample: 'Cô ấy đã đỗ kỳ thi công chức.',
  },
  {
    word: '회사원',
    topic: 'Nghề nghiệp',
    hint: 'Người làm việc trong công ty',
    koreanExample: '그는 대기업 회사원입니다.',
    vietnameseExample: 'Anh ấy là nhân viên của một công ty lớn.',
  },
  {
    word: '엔지니어',
    topic: 'Nghề nghiệp',
    hint: 'Người làm công việc kỹ thuật',
    koreanExample: '그녀는 소프트웨어 엔지니어로 일합니다.',
    vietnameseExample: 'Cô ấy làm việc như một kỹ sư phần mềm.',
  },
  {
    word: '프로그래머',
    topic: 'Nghề nghiệp',
    hint: 'Người viết mã máy tính',
    koreanExample: '프로그래머는 컴퓨터 프로그램을 개발합니다.',
    vietnameseExample: 'Lập trình viên phát triển các chương trình máy tính.',
  },
  {
    word: '디자이너',
    topic: 'Nghề nghiệp',
    hint: 'Người thiết kế sản phẩm, đồ họa,...',
    koreanExample: '그녀는 유명한 패션 디자이너입니다.',
    vietnameseExample: 'Cô ấy là nhà thiết kế thời trang nổi tiếng.',
  },
  {
    word: '기자',
    topic: 'Nghề nghiệp',
    hint: 'Người viết tin tức cho báo chí',
    koreanExample: '기자는 뉴스를 취재합니다.',
    vietnameseExample: 'Phóng viên tìm hiểu tin tức.',
  },
  {
    word: '가수',
    topic: 'Nghề nghiệp',
    hint: 'Người hát chuyên nghiệp',
    koreanExample: '그는 인기 있는 가수입니다.',
    vietnameseExample: 'Anh ấy là ca sĩ nổi tiếng.',
  },
  {
    word: '배우',
    topic: 'Nghề nghiệp',
    hint: 'Người đóng phim hoặc kịch',
    koreanExample: '그녀는 유명한 영화 배우입니다.',
    vietnameseExample: 'Cô ấy là diễn viên phim nổi tiếng.',
  },
  {
    word: '작가',
    topic: 'Nghề nghiệp',
    hint: 'Người viết sách hoặc kịch bản',
    koreanExample: '그는 베스트셀러 작가입니다.',
    vietnameseExample: 'Anh ấy là tác giả sách bán chạy.',
  },
  {
    word: '번역가',
    topic: 'Nghề nghiệp',
    hint: 'Người dịch từ ngôn ngữ này sang ngôn ngữ khác',
    koreanExample: '번역가는 여러 언어를 구사합니다.',
    vietnameseExample: 'Phiên dịch viên sử dụng được nhiều ngôn ngữ.',
  },
  {
    word: '운전기사',
    topic: 'Nghề nghiệp',
    hint: 'Người lái xe chuyên nghiệp',
    koreanExample: '그는 버스 운전기사입니다.',
    vietnameseExample: 'Anh ấy là tài xế xe buýt.',
  },
  {
    word: '건축가',
    topic: 'Nghề nghiệp',
    hint: 'Người thiết kế tòa nhà',
    koreanExample: '건축가는 건물을 설계합니다.',
    vietnameseExample: 'Kiến trúc sư thiết kế tòa nhà.',
  },
  {
    word: '비서',
    topic: 'Nghề nghiệp',
    hint: 'Người hỗ trợ công việc cho người quản lý',
    koreanExample: '그녀는 대표이사의 비서로 일합니다.',
    vietnameseExample: 'Cô ấy làm thư ký cho giám đốc điều hành.',
  },
  {
    word: '농부',
    topic: 'Nghề nghiệp',
    hint: 'Người làm nghề nông',
    koreanExample: '농부는 작물을 재배합니다.',
    vietnameseExample: 'Nông dân trồng trọt cây trồng.',
  },
  {
    word: '어부',
    topic: 'Nghề nghiệp',
    hint: 'Người đánh bắt cá',
    koreanExample: '어부는 바다에서 물고기를 잡습니다.',
    vietnameseExample: 'Ngư dân bắt cá từ biển.',
  },
  {
    word: '목수',
    topic: 'Nghề nghiệp',
    hint: 'Người làm đồ gỗ',
    koreanExample: '목수는 나무로 가구를 만듭니다.',
    vietnameseExample: 'Thợ mộc làm đồ nội thất từ gỗ.',
  },
  {
    word: '미용사',
    topic: 'Nghề nghiệp',
    hint: 'Người làm tóc',
    koreanExample: '미용사는 손님의 머리를 스타일링합니다.',
    vietnameseExample: 'Thợ làm tóc tạo kiểu tóc cho khách hàng.',
  },
  {
    word: '화가',
    topic: 'Nghề nghiệp',
    hint: 'Người vẽ tranh',
    koreanExample: '그는 유명한 화가입니다.',
    vietnameseExample: 'Anh ấy là họa sĩ nổi tiếng.',
  },
  {
    word: '경영자',
    topic: 'Nghề nghiệp',
    hint: 'Người quản lý công ty',
    koreanExample: '그녀는 성공적인 경영자입니다.',
    vietnameseExample: 'Cô ấy là nhà quản lý thành công.',
  },
  {
    word: '회계사',
    topic: 'Nghề nghiệp',
    hint: 'Người làm việc với sổ sách tài chính',
    koreanExample: '회계사는 기업의 재무 상태를 관리합니다.',
    vietnameseExample:
      'Kế toán viên quản lý tình hình tài chính của doanh nghiệp.',
  },
  {
    word: '약사',
    topic: 'Nghề nghiệp',
    hint: 'Người bán thuốc tại hiệu thuốc',
    koreanExample: '약사는 약에 대한 지식이 풍부합니다.',
    vietnameseExample: 'Dược sĩ có kiến thức phong phú về thuốc.',
  },
  {
    word: '판매원',
    topic: 'Nghề nghiệp',
    hint: 'Người bán hàng tại cửa hàng',
    koreanExample: '판매원은 고객을 도와줍니다.',
    vietnameseExample: 'Nhân viên bán hàng giúp đỡ khách hàng.',
  },
  {
    word: '군인',
    topic: 'Nghề nghiệp',
    hint: 'Người phục vụ trong quân đội',
    koreanExample: '그는 용감한 군인입니다.',
    vietnameseExample: 'Anh ấy là một người lính dũng cảm.',
  },
  {
    word: '김치',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Món ăn truyền thống làm từ rau cải thảo ủ chua cay',
    koreanExample: '김치는 한국의 대표적인 전통 음식입니다.',
    vietnameseExample: 'Kimchi là món ăn truyền thống đại diện của Hàn Quốc.',
  },
  {
    word: '비빔밥',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Cơm trộn với nhiều loại rau và thịt',
    koreanExample: '전주 비빔밥은 맛있기로 유명합니다.',
    vietnameseExample: 'Bibimbap Jeonju nổi tiếng là món ngon.',
  },
  {
    word: '불고기',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Thịt bò nướng tẩm ướp ngọt',
    koreanExample: '불고기는 한국의 대표적인 고기 요리입니다.',
    vietnameseExample: 'Bulgogi là món thịt đại diện của Hàn Quốc.',
  },
  {
    word: '삼겹살',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Thịt ba chỉ nướng',
    koreanExample: '친구들과 삼겹살을 먹으러 갔어요.',
    vietnameseExample: 'Tôi đã đi ăn thịt ba chỉ nướng cùng bạn bè.',
  },
  {
    word: '김밥',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Cơm cuộn rong biển với nhiều loại nhân',
    koreanExample: '소풍에 김밥을 싸 갔어요.',
    vietnameseExample: 'Tôi đã mang kimbap đi dã ngoại.',
  },
  {
    word: '떡볶이',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Bánh gạo xào cay',
    koreanExample: '떡볶이는 매운 한국 길거리 음식입니다.',
    vietnameseExample: 'Tteokbokki là món ăn đường phố cay của Hàn Quốc.',
  },
  {
    word: '된장찌개',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Canh đậu tương lên men',
    koreanExample: '된장찌개는 건강에 좋습니다.',
    vietnameseExample: 'Canh đậu tương rất tốt cho sức khỏe.',
  },
  {
    word: '김치찌개',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Canh kim chi thường có thịt heo',
    koreanExample: '추운 날에는 김치찌개가 생각나요.',
    vietnameseExample: 'Vào ngày lạnh, tôi thèm canh kim chi.',
  },
  {
    word: '순두부찌개',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Canh đậu phụ mềm cay',
    koreanExample: '순두부찌개는 매콤하고 부드럽습니다.',
    vietnameseExample: 'Canh đậu phụ mềm vừa cay vừa mềm.',
  },
  {
    word: '라면',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Mì ăn liền',
    koreanExample: '한국 라면은 세계적으로 인기가 있습니다.',
    vietnameseExample: 'Mì ăn liền Hàn Quốc được ưa chuộng trên toàn thế giới.',
  },
  {
    word: '잡채',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Miến xào với rau và thịt',
    koreanExample: '명절에는 보통 잡채를 만듭니다.',
    vietnameseExample: 'Japchae thường được làm vào các dịp lễ.',
  },
  {
    word: '갈비',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Sườn bò hoặc heo nướng',
    koreanExample: '갈비는 특별한 날에 먹는 고급 음식입니다.',
    vietnameseExample:
      'Sườn nướng là món ăn cao cấp dùng trong những ngày đặc biệt.',
  },
  {
    word: '삼계탕',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Canh gà hầm nhân sâm',
    koreanExample: '여름에는 삼계탕을 먹으면 원기회복에 좋습니다.',
    vietnameseExample:
      'Ăn canh gà nhân sâm vào mùa hè tốt cho việc phục hồi sức khỏe.',
  },
  {
    word: '냉면',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Mì lạnh',
    koreanExample: '더운 여름에는 냉면이 인기가 있습니다.',
    vietnameseExample: 'Mì lạnh rất phổ biến vào mùa hè nóng bức.',
  },
  {
    word: '부침개',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Bánh chiên kiểu Hàn Quốc',
    koreanExample: '비 오는 날에는 부침개가 생각납니다.',
    vietnameseExample: 'Vào ngày mưa, tôi thèm bánh chiên Hàn Quốc.',
  },
  {
    word: '만두',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Bánh bao nhân thịt và rau',
    koreanExample: '만두는 찌거나 튀기거나 볶을 수 있습니다.',
    vietnameseExample: 'Bánh mandu có thể hấp, chiên hoặc xào.',
  },
  {
    word: '떡국',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Canh bánh gạo ăn vào dịp Tết',
    koreanExample: '설날에는 떡국을 먹는 전통이 있습니다.',
    vietnameseExample:
      'Có truyền thống ăn canh bánh gạo vào dịp Tết Nguyên Đán.',
  },
  {
    word: '갈비탕',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Canh sườn bò hầm',
    koreanExample: '갈비탕은 뼈에 붙은 고기가 부드럽습니다.',
    vietnameseExample: 'Thịt bám vào xương trong canh sườn bò rất mềm.',
  },
  {
    word: '제육볶음',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Thịt heo xào cay',
    koreanExample: '제육볶음은 매콤한 한국 요리입니다.',
    vietnameseExample: 'Thịt heo xào cay là món ăn cay của Hàn Quốc.',
  },
  {
    word: '죽',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Cháo Hàn Quốc',
    koreanExample: '아플 때는 죽을 먹으면 좋습니다.',
    vietnameseExample: 'Khi bị ốm, ăn cháo rất tốt.',
  },
  {
    word: '파전',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Bánh chiên hành',
    koreanExample: '비 오는 날에는 파전과 막걸리가 잘 어울립니다.',
    vietnameseExample:
      'Vào ngày mưa, bánh chiên hành rất hợp với rượu makgeolli.',
  },
  {
    word: '호떡',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Bánh rán nhân đường và hạt',
    koreanExample: '겨울에는 길거리에서 호떡을 많이 팝니다.',
    vietnameseExample: 'Vào mùa đông, bánh hotteok được bán nhiều ở đường phố.',
  },
  {
    word: '육개장',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Canh thịt bò cay',
    koreanExample: '육개장은 매콤한 쇠고기 국입니다.',
    vietnameseExample: 'Yukgaejang là canh thịt bò cay.',
  },
  {
    word: '설렁탕',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Canh xương bò hầm trắng',
    koreanExample: '설렁탕은 뼈를 오래 끓여 만듭니다.',
    vietnameseExample:
      'Seolleongtang được làm bằng cách hầm xương trong thời gian dài.',
  },
  {
    word: '칼국수',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Mì cắt sợi trong nước dùng',
    koreanExample: '칼국수는 손으로 반죽해서 칼로 썬 면입니다.',
    vietnameseExample: 'Kalguksu là mì nhào bằng tay và cắt bằng dao.',
  },
  {
    word: '물냉면',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Mì lạnh trong nước dùng',
    koreanExample: '여름에는 시원한 물냉면이 인기가 있습니다.',
    vietnameseExample: 'Vào mùa hè, mì lạnh mát rất phổ biến.',
  },
  {
    word: '비빔냉면',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Mì lạnh trộn',
    koreanExample: '비빔냉면은 매콤한 맛이 특징입니다.',
    vietnameseExample: 'Mì lạnh trộn có đặc trưng là vị cay.',
  },
  {
    word: '닭갈비',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Thịt gà xào cay với rau và bánh gạo',
    koreanExample: '춘천은 닭갈비로 유명합니다.',
    vietnameseExample: 'Thành phố Chuncheon nổi tiếng với món dakgalbi.',
  },
  {
    word: '보쌈',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Thịt heo luộc ăn với lá cuốn',
    koreanExample: '보쌈은 김치와 함께 먹으면 맛있습니다.',
    vietnameseExample: 'Bossam rất ngon khi ăn với kim chi.',
  },
  {
    word: '수제비',
    topic: 'Món ăn Hàn Quốc',
    hint: 'Canh với bột nhào thả',
    koreanExample: '비 오는 날에는 따뜻한 수제비가 생각납니다.',
    vietnameseExample: 'Vào ngày mưa, tôi thèm canh sujebi ấm.',
  },
  {
    word: '머리',
    topic: 'Bộ phận cơ thể',
    hint: 'Phần trên cùng của cơ thể, nơi có não bộ',
    koreanExample: '머리가 아파서 약을 먹었어요.',
    vietnameseExample: 'Tôi đã uống thuốc vì đau đầu.',
  },
  {
    word: '얼굴',
    topic: 'Bộ phận cơ thể',
    hint: 'Phần trước của đầu gồm mắt, mũi và miệng',
    koreanExample: '거울에서 얼굴을 봤어요.',
    vietnameseExample: 'Tôi đã nhìn khuôn mặt mình trong gương.',
  },
  {
    word: '눈',
    topic: 'Bộ phận cơ thể',
    hint: 'Cơ quan thị giác, dùng để nhìn',
    koreanExample: '그녀는 큰 눈이 매력적이에요.',
    vietnameseExample: 'Cô ấy có đôi mắt to rất quyến rũ.',
  },
  {
    word: '코',
    topic: 'Bộ phận cơ thể',
    hint: 'Cơ quan khứu giác ở giữa mặt, dùng để ngửi',
    koreanExample: '감기에 걸려서 코가 막혔어요.',
    vietnameseExample: 'Tôi bị cảm lạnh nên mũi bị nghẹt.',
  },
  {
    word: '입',
    topic: 'Bộ phận cơ thể',
    hint: 'Phần mở trên mặt, dùng để ăn và nói',
    koreanExample: '음식을 먹을 때 입을 크게 벌리지 마세요.',
    vietnameseExample: 'Đừng mở miệng quá to khi ăn.',
  },
  {
    word: '귀',
    topic: 'Bộ phận cơ thể',
    hint: 'Cơ quan thính giác ở hai bên đầu, dùng để nghe',
    koreanExample: '음악을 들을 때 귀에 이어폰을 꽂아요.',
    vietnameseExample: 'Tôi đeo tai nghe vào tai khi nghe nhạc.',
  },
  {
    word: '목',
    topic: 'Bộ phận cơ thể',
    hint: 'Phần nối giữa đầu và thân',
    koreanExample: '목이 아파서 목소리가 안 나와요.',
    vietnameseExample: 'Tôi bị đau cổ nên không thể nói được.',
  },
  {
    word: '어깨',
    topic: 'Bộ phận cơ thể',
    hint: 'Phần nối giữa cánh tay và thân trên',
    koreanExample: '무거운 가방을 들어서 어깨가 아파요.',
    vietnameseExample: 'Vai tôi đau vì xách túi nặng.',
  },
  {
    word: '팔',
    topic: 'Bộ phận cơ thể',
    hint: 'Phần chi trên từ vai đến bàn tay',
    koreanExample: '운동을 많이 해서 팔이 근육질이에요.',
    vietnameseExample: 'Cánh tay tôi rất cơ bắp vì tập thể dục nhiều.',
  },
  {
    word: '손',
    topic: 'Bộ phận cơ thể',
    hint: 'Phần cuối của cánh tay, có ngón tay',
    koreanExample: '손을 씻고 밥을 먹어요.',
    vietnameseExample: 'Tôi rửa tay trước khi ăn cơm.',
  },
  {
    word: '다리',
    topic: 'Bộ phận cơ thể',
    hint: 'Phần chi dưới dùng để đi và đứng',
    koreanExample: '계단을 많이 올라가서 다리가 피곤해요.',
    vietnameseExample: 'Chân tôi mỏi vì leo nhiều cầu thang.',
  },
  {
    word: '발',
    topic: 'Bộ phận cơ thể',
    hint: 'Phần cuối của chân, tiếp xúc với mặt đất khi đi',
    koreanExample: '긴 시간 서 있어서 발이 아파요.',
    vietnameseExample: 'Bàn chân tôi đau vì đứng lâu.',
  },
  {
    word: '가슴',
    topic: 'Bộ phận cơ thể',
    hint: 'Phần ngực, nơi có tim',
    koreanExample: '달리기를 하면 가슴이 두근거려요.',
    vietnameseExample: 'Tim tôi đập nhanh khi chạy bộ.',
  },
  {
    word: '배',
    topic: 'Bộ phận cơ thể',
    hint: 'Phần bụng, nơi có dạ dày',
    koreanExample: '많이 먹어서 배가 불러요.',
    vietnameseExample: 'Tôi no bụng vì ăn nhiều.',
  },
  {
    word: '허리',
    topic: 'Bộ phận cơ thể',
    hint: 'Phần giữa cơ thể, nối thân trên và thân dưới',
    koreanExample: '무거운 것을 들어서 허리가 아파요.',
    vietnameseExample: 'Lưng tôi đau vì nhấc vật nặng.',
  },
  {
    word: '무릎',
    topic: 'Bộ phận cơ thể',
    hint: 'Khớp giữa đùi và cẳng chân',
    koreanExample: '계단을 오르내릴 때 무릎이 아파요.',
    vietnameseExample: 'Đầu gối tôi đau khi lên xuống cầu thang.',
  },
  {
    word: '손가락',
    topic: 'Bộ phận cơ thể',
    hint: 'Phần nhỏ và dài ở cuối bàn tay',
    koreanExample: '피아노를 칠 때 손가락을 유연하게 움직여요.',
    vietnameseExample: 'Tôi di chuyển ngón tay linh hoạt khi chơi đàn piano.',
  },
  {
    word: '발가락',
    topic: 'Bộ phận cơ thể',
    hint: 'Phần nhỏ và dài ở cuối bàn chân',
    koreanExample: '좁은 신발을 신어서 발가락이 아파요.',
    vietnameseExample: 'Ngón chân tôi đau vì mang giày chật.',
  },
  {
    word: '등',
    topic: 'Bộ phận cơ thể',
    hint: 'Phần sau của thân trên',
    koreanExample: '자세가 안 좋아서 등이 자주 아파요.',
    vietnameseExample: 'Lưng tôi thường xuyên đau vì tư thế không tốt.',
  },
  {
    word: '엉덩이',
    topic: 'Bộ phận cơ thể',
    hint: 'Phần sau dưới của thân, dùng để ngồi',
    koreanExample: '오래 앉아 있어서 엉덩이가 아파요.',
    vietnameseExample: 'Mông tôi đau vì ngồi lâu.',
  },
  {
    word: '한국',
    topic: 'Tên quốc gia',
    hint: 'Đất nước Nam Hàn, nơi nói tiếng Hàn',
    koreanExample: '저는 한국에서 왔습니다.',
    vietnameseExample: 'Tôi đến từ Hàn Quốc.',
  },
  {
    word: '베트남',
    topic: 'Tên quốc gia',
    hint: 'Đất nước Việt Nam ở Đông Nam Á',
    koreanExample: '베트남은 아름다운 나라입니다.',
    vietnameseExample: 'Việt Nam là một đất nước xinh đẹp.',
  },
  {
    word: '중국',
    topic: 'Tên quốc gia',
    hint: 'Đất nước lớn nhất ở châu Á',
    koreanExample: '중국은 인구가 많은 나라입니다.',
    vietnameseExample: 'Trung Quốc là quốc gia đông dân.',
  },
  {
    word: '일본',
    topic: 'Tên quốc gia',
    hint: 'Đất nước hình chữ nhật ở phía đông Hàn Quốc',
    koreanExample: '일본은 섬나라입니다.',
    vietnameseExample: 'Nhật Bản là một quốc gia đảo.',
  },
  {
    word: '미국',
    topic: 'Tên quốc gia',
    hint: 'Đất nước Hoa Kỳ ở Bắc Mỹ',
    koreanExample: '미국은 50개 주로 이루어져 있습니다.',
    vietnameseExample: 'Hoa Kỳ bao gồm 50 tiểu bang.',
  },
  {
    word: '영국',
    topic: 'Tên quốc gia',
    hint: 'Đất nước Anh ở châu Âu',
    koreanExample: '영국의 수도는 런던입니다.',
    vietnameseExample: 'Thủ đô của Anh là London.',
  },
  {
    word: '프랑스',
    topic: 'Tên quốc gia',
    hint: 'Đất nước Pháp ở châu Âu',
    koreanExample: '프랑스는 에펠탑으로 유명합니다.',
    vietnameseExample: 'Pháp nổi tiếng với tháp Eiffel.',
  },
  {
    word: '독일',
    topic: 'Tên quốc gia',
    hint: 'Đất nước Đức ở châu Âu',
    koreanExample: '독일은 자동차 산업이 발달했습니다.',
    vietnameseExample: 'Đức có ngành công nghiệp ô tô phát triển.',
  },
  {
    word: '이탈리아',
    topic: 'Tên quốc gia',
    hint: 'Đất nước Ý ở nam châu Âu',
    koreanExample: '이탈리아는 피자와 파스타로 유명합니다.',
    vietnameseExample: 'Ý nổi tiếng với pizza và pasta.',
  },
  {
    word: '스페인',
    topic: 'Tên quốc gia',
    hint: 'Đất nước Tây Ban Nha ở châu Âu',
    koreanExample: '스페인은 플라멩코 춤으로 유명합니다.',
    vietnameseExample: 'Tây Ban Nha nổi tiếng với điệu nhảy Flamenco.',
  },
  {
    word: '러시아',
    topic: 'Tên quốc gia',
    hint: 'Đất nước Nga, rộng lớn nhất thế giới',
    koreanExample: '러시아는 세계에서 가장 넓은 나라입니다.',
    vietnameseExample: 'Nga là quốc gia rộng lớn nhất thế giới.',
  },
  {
    word: '캐나다',
    topic: 'Tên quốc gia',
    hint: 'Đất nước Canada ở Bắc Mỹ',
    koreanExample: '캐나다는 자연 경관이 아름답습니다.',
    vietnameseExample: 'Canada có cảnh quan thiên nhiên đẹp.',
  },
  {
    word: '호주',
    topic: 'Tên quốc gia',
    hint: 'Đất nước Australia, cả một lục địa',
    koreanExample: '호주는 캥거루로 유명합니다.',
    vietnameseExample: 'Australia nổi tiếng với loài kangaroo.',
  },
  {
    word: '인도',
    topic: 'Tên quốc gia',
    hint: 'Đất nước Ấn Độ ở Nam Á',
    koreanExample: '인도는 인구가 많은 나라입니다.',
    vietnameseExample: 'Ấn Độ là quốc gia đông dân.',
  },
  {
    word: '태국',
    topic: 'Tên quốc gia',
    hint: 'Đất nước Thái Lan ở Đông Nam Á',
    koreanExample: '태국은 관광지로 유명합니다.',
    vietnameseExample: 'Thái Lan nổi tiếng là điểm du lịch.',
  },
  {
    word: '싱가포르',
    topic: 'Tên quốc gia',
    hint: 'Đất nước Singapore, một thành phố-quốc gia',
    koreanExample: '싱가포르는 작지만 경제가 발달했습니다.',
    vietnameseExample: 'Singapore nhỏ nhưng có nền kinh tế phát triển.',
  },
  {
    word: '인도네시아',
    topic: 'Tên quốc gia',
    hint: 'Đất nước Indonesia, nhiều đảo nhất thế giới',
    koreanExample: '인도네시아는 많은 섬으로 이루어져 있습니다.',
    vietnameseExample: 'Indonesia bao gồm nhiều hòn đảo.',
  },
  {
    word: '말레이시아',
    topic: 'Tên quốc gia',
    hint: 'Đất nước Malaysia ở Đông Nam Á',
    koreanExample: '말레이시아의 수도는 쿠알라룸푸르입니다.',
    vietnameseExample: 'Thủ đô của Malaysia là Kuala Lumpur.',
  },
  {
    word: '캄보디아',
    topic: 'Tên quốc gia',
    hint: 'Đất nước Campuchia ở Đông Nam Á',
    koreanExample: '캄보디아는 앙코르 와트로 유명합니다.',
    vietnameseExample: 'Campuchia nổi tiếng với Angkor Wat.',
  },
  {
    word: '필리핀',
    topic: 'Tên quốc gia',
    hint: 'Đất nước Philippines ở Đông Nam Á',
    koreanExample: '필리핀은 많은 섬으로 이루어진 나라입니다.',
    vietnameseExample: 'Philippines là quốc gia bao gồm nhiều đảo.',
  },
  {
    word: '윤석열',
    topic: 'Tổng thống Hàn Quốc',
    hint: 'Tổng thống thứ 20 của Hàn Quốc từ năm 2022',
    koreanExample: '윤석열 대통령은 2022년에 취임했습니다.',
    vietnameseExample: 'Tổng thống Yoon Suk-yeol nhậm chức vào năm 2022.',
  },
  {
    word: '문재인',
    topic: 'Tổng thống Hàn Quốc',
    hint: 'Tổng thống thứ 19 của Hàn Quốc (2017-2022)',
    koreanExample: '문재인 대통령은 2017년부터 2022년까지 재임했습니다.',
    vietnameseExample: 'Tổng thống Moon Jae-in tại vị từ năm 2017 đến 2022.',
  },
  {
    word: '박근혜',
    topic: 'Tổng thống Hàn Quốc',
    hint: 'Tổng thống thứ 18 của Hàn Quốc, nữ tổng thống đầu tiên',
    koreanExample: '박근혜는 한국 최초의 여성 대통령이었습니다.',
    vietnameseExample: 'Park Geun-hye là nữ tổng thống đầu tiên của Hàn Quốc.',
  },
  {
    word: '이명박',
    topic: 'Tổng thống Hàn Quốc',
    hint: 'Tổng thống thứ 17 của Hàn Quốc (2008-2013)',
    koreanExample: '이명박 대통령은 기업인 출신입니다.',
    vietnameseExample: 'Tổng thống Lee Myung-bak có xuất thân là doanh nhân.',
  },
  {
    word: '노무현',
    topic: 'Tổng thống Hàn Quốc',
    hint: 'Tổng thống thứ 16 của Hàn Quốc (2003-2008)',
    koreanExample: '노무현 대통령은 2003년부터 2008년까지 재임했습니다.',
    vietnameseExample: 'Tổng thống Roh Moo-hyun tại vị từ năm 2003 đến 2008.',
  },
  {
    word: '김대중',
    topic: 'Tổng thống Hàn Quốc',
    hint: 'Tổng thống thứ 15 của Hàn Quốc, đạt giải Nobel Hòa bình',
    koreanExample: '김대중 대통령은 노벨 평화상을 받았습니다.',
    vietnameseExample:
      'Tổng thống Kim Dae-jung đã được trao giải Nobel Hòa bình.',
  },
  {
    word: '김영삼',
    topic: 'Tổng thống Hàn Quốc',
    hint: 'Tổng thống thứ 14 của Hàn Quốc (1993-1998)',
    koreanExample: '김영삼 대통령은 한국의 첫 문민 대통령이었습니다.',
    vietnameseExample:
      'Tổng thống Kim Young-sam là tổng thống dân sự đầu tiên của Hàn Quốc.',
  },
  {
    word: '노태우',
    topic: 'Tổng thống Hàn Quốc',
    hint: 'Tổng thống thứ 13 của Hàn Quốc (1988-1993)',
    koreanExample: '노태우 대통령은 군인 출신입니다.',
    vietnameseExample: 'Tổng thống Roh Tae-woo có xuất thân là quân nhân.',
  },
  {
    word: '전두환',
    topic: 'Tổng thống Hàn Quốc',
    hint: 'Tổng thống thứ 12 của Hàn Quốc (1980-1988)',
    koreanExample: '전두환 대통령은 1980년부터 1988년까지 재임했습니다.',
    vietnameseExample: 'Tổng thống Chun Doo-hwan tại vị từ năm 1980 đến 1988.',
  },
  {
    word: '박정희',
    topic: 'Tổng thống Hàn Quốc',
    hint: 'Tổng thống thứ 5-9 của Hàn Quốc (1963-1979)',
    koreanExample: '박정희 대통령은 한국의 경제 발전에 기여했습니다.',
    vietnameseExample:
      'Tổng thống Park Chung-hee đã đóng góp vào sự phát triển kinh tế của Hàn Quốc.',
  },
  {
    word: '이승만',
    topic: 'Tổng thống Hàn Quốc',
    hint: 'Tổng thống đầu tiên của Hàn Quốc (1948-1960)',
    koreanExample: '이승만은 대한민국의 초대 대통령이었습니다.',
    vietnameseExample: 'Syngman Rhee là tổng thống đầu tiên của Hàn Quốc.',
  },
  {
    word: '혼코노',
    topic: 'Từ ngữ mới của Hàn Quốc',
    hint: "'혼자 코인 노래방'의 줄임말, đi hát karaoke xu một mình",
    koreanExample: '오늘 스트레스 풀려고 혼코노 갔어요.',
    vietnameseExample:
      'Hôm nay tôi đã đi hát karaoke một mình để giải tỏa căng thẳng.',
  },
  {
    word: '좋댓구알',
    topic: 'Từ ngữ mới của Hàn Quốc',
    hint: "'좋아요, 댓글, 구독, 알림설정'의 줄임말, like, comment, subscribe, bật thông báo",
    koreanExample: '이 영상이 마음에 들면 좋댓구알 부탁드려요!',
    vietnameseExample:
      'Nếu bạn thích video này, hãy like, comment, subscribe và bật thông báo!',
  },
  {
    word: '맴찢',
    topic: 'Từ ngữ mới của Hàn Quốc',
    hint: "'마음이 찢어진다'의 줄임말, trái tim tan vỡ",
    koreanExample: '슬픈 영화를 보고 맴찢했어요.',
    vietnameseExample: 'Sau khi xem bộ phim buồn, trái tim tôi như vỡ tan.',
  },
  {
    word: '세젤예',
    topic: 'Từ ngữ mới của Hàn Quốc',
    hint: "'세상에서 제일 예쁜'의 줄임말, đẹp nhất thế giới",
    koreanExample: '이 드레스는 세젤예예요!',
    vietnameseExample: 'Chiếc váy này đẹp nhất thế giới!',
  },
  {
    word: '갑분싸',
    topic: 'Từ ngữ mới của Hàn Quốc',
    hint: "'갑자기 분위기 싸해짐'의 줄임말, không khí đột nhiên trở nên ngượng ngùng",
    koreanExample: '그 말 한마디에 갑분싸가 됐어요.',
    vietnameseExample:
      'Chỉ một câu nói đó đã khiến không khí đột nhiên trở nên ngượng ngùng.',
  },
  {
    word: '팩폭',
    topic: 'Từ ngữ mới của Hàn Quốc',
    hint: "'팩트 폭행'의 줄임말, nói thẳng sự thật gây sốc",
    koreanExample: '친구가 팩폭해서 기분이 안 좋아요.',
    vietnameseExample:
      'Tôi cảm thấy không thoải mái vì bạn tôi đã nói thẳng sự thật.',
  },
  {
    word: '꾸안꾸',
    topic: 'Từ ngữ mới của Hàn Quốc',
    hint: "Viết tắt của '꾸민 듯 안 꾸민 듯' - vẻ ngoài như trang điểm mà không trang điểm",
    koreanExample: '오늘 그녀는 꾸안꾸 스타일로 나왔어요.',
    vietnameseExample:
      'Hôm nay cô ấy xuất hiện với phong cách trang điểm mà như không trang điểm.',
  },
  {
    word: '인싸',
    topic: 'Từ ngữ mới của Hàn Quốc',
    hint: "'인사이더(insider)'의 줄임말, 인기 있는 사람",
    koreanExample: '그는 우리 학교의 인싸예요.',
    vietnameseExample: 'Anh ấy là người nổi tiếng ở trường chúng tôi.',
  },
  {
    word: '맛집',
    topic: 'Từ ngữ mới của Hàn Quốc',
    hint: 'Nhà hàng ngon, quán ăn nổi tiếng với món ăn ngon',
    koreanExample: '이 동네에는 맛집이 많아요.',
    vietnameseExample: 'Khu vực này có nhiều quán ăn ngon.',
  },
  {
    word: '올리브영',
    topic: 'Địa điểm Hàn Quốc',
    hint: 'Chuỗi cửa hàng mỹ phẩm và chăm sóc sức khỏe lớn nhất Hàn Quốc',
    koreanExample: '화장품을 사러 올리브영에 갔어요.',
    vietnameseExample: 'Tôi đã đến Olive Young để mua mỹ phẩm.',
  },
  {
    word: '서울대학교',
    topic: 'Trường đại học Hàn Quốc',
    hint: 'Đại học Quốc gia Seoul, trường đại học hàng đầu Hàn Quốc',
    koreanExample: '그는 서울대학교 의대에 다닙니다.',
    vietnameseExample: 'Anh ấy học tại Khoa Y, Đại học Quốc gia Seoul.',
  },
  {
    word: '연세대학교',
    topic: 'Trường đại học Hàn Quốc',
    hint: 'Đại học Yonsei, một trong những trường đại học hàng đầu của Hàn Quốc',
    koreanExample: '연세대학교는 서울 신촌에 있습니다.',
    vietnameseExample: 'Đại học Yonsei nằm ở khu vực Sinchon, Seoul.',
  },
  {
    word: '고려대학교',
    topic: 'Trường đại học Hàn Quốc',
    hint: 'Đại học Korea, một trong ba trường đại học hàng đầu tại Hàn Quốc',
    koreanExample: '고려대학교는 오랜 역사를 가진 명문대학교입니다.',
    vietnameseExample:
      'Đại học Korea là một trường đại học danh tiếng với lịch sử lâu đời.',
  },
  {
    word: '카이스트',
    topic: 'Trường đại học Hàn Quốc',
    hint: 'Viện Khoa học và Công nghệ Tiên tiến Hàn Quốc, nổi tiếng về kỹ thuật và khoa học',
    koreanExample: '카이스트는 대전에 위치해 있습니다.',
    vietnameseExample: 'KAIST nằm ở Daejeon.',
  },
  {
    word: '성균관대학교',
    topic: 'Trường đại học Hàn Quốc',
    hint: 'Đại học Sungkyunkwan, một trong những trường đại học lâu đời nhất Hàn Quốc',
    koreanExample: '성균관대학교는 삼성그룹과 밀접한 관계가 있습니다.',
    vietnameseExample:
      'Đại học Sungkyunkwan có mối quan hệ chặt chẽ với tập đoàn Samsung.',
  },
  {
    word: '한양대학교',
    topic: 'Trường đại học Hàn Quốc',
    hint: 'Đại học Hanyang, nổi tiếng về kỹ thuật và kinh doanh',
    koreanExample: '한양대학교는 서울과 안산에 캠퍼스가 있습니다.',
    vietnameseExample: 'Đại học Hanyang có các cơ sở ở Seoul và Ansan.',
  },
  {
    word: '이화여자대학교',
    topic: 'Trường đại học Hàn Quốc',
    hint: 'Đại học Nữ Ewha, trường đại học nữ lớn nhất thế giới',
    koreanExample: '이화여자대학교는 여성 교육의 선구자입니다.',
    vietnameseExample:
      'Đại học Nữ Ewha là người tiên phong trong giáo dục phụ nữ.',
  },
  {
    word: '포항공과대학교',
    topic: 'Trường đại học Hàn Quốc',
    hint: 'Viện Khoa học và Công nghệ Pohang, nổi tiếng về nghiên cứu khoa học',
    koreanExample: '포항공과대학교는 연구중심 대학입니다.',
    vietnameseExample:
      'Viện Khoa học và Công nghệ Pohang là một trường đại học tập trung vào nghiên cứu.',
  },
  {
    word: '서강대학교',
    topic: 'Trường đại học Hàn Quốc',
    hint: 'Đại học Sogang, được biết đến với chương trình giảng dạy ngôn ngữ xuất sắc',
    koreanExample: '서강대학교는 인문학이 강한 학교입니다.',
    vietnameseExample: 'Đại học Sogang mạnh về khoa học nhân văn.',
  },
  {
    word: '중앙대학교',
    topic: 'Trường đại học Hàn Quốc',
    hint: 'Đại học Chung-Ang, nổi tiếng về nghệ thuật và điện ảnh',
    koreanExample: '중앙대학교는 예술과 영화 분야에서 유명합니다.',
    vietnameseExample:
      'Đại học Chung-Ang nổi tiếng trong lĩnh vực nghệ thuật và điện ảnh.',
  },
  {
    word: '배추',
    topic: 'Rau củ',
    hint: 'Bắp cải trắng Hàn Quốc, nguyên liệu chính làm kimchi',
    koreanExample: '김치를 만들기 위해 배추를 샀어요.',
    vietnameseExample: 'Tôi đã mua bắp cải trắng để làm kimchi.',
  },
  {
    word: '무',
    topic: 'Rau củ',
    hint: 'Củ cải trắng, thường dùng trong kimchi và canh',
    koreanExample: '무는 김치와 국에 많이 사용해요.',
    vietnameseExample: 'Củ cải trắng được sử dụng nhiều trong kimchi và canh.',
  },
  {
    word: '당근',
    topic: 'Rau củ',
    hint: 'Cà rốt, rau củ màu cam giàu vitamin A',
    koreanExample: '당근은 비타민 A가 풍부해요.',
    vietnameseExample: 'Cà rốt giàu vitamin A.',
  },
  {
    word: '감자',
    topic: 'Rau củ',
    hint: 'Khoai tây, thường được luộc, chiên hoặc nấu canh',
    koreanExample: '감자를 삶아서 먹었어요.',
    vietnameseExample: 'Tôi đã luộc khoai tây để ăn.',
  },
  {
    word: '고구마',
    topic: 'Rau củ',
    hint: 'Khoai lang, thường được nướng hoặc hấp',
    koreanExample: '가을에는 고구마를 많이 먹어요.',
    vietnameseExample: 'Vào mùa thu, chúng tôi ăn nhiều khoai lang.',
  },
  {
    word: '양파',
    topic: 'Rau củ',
    hint: 'Hành tây, gia vị phổ biến trong nhiều món ăn',
    koreanExample: '요리할 때 양파를 넣으면 맛있어요.',
    vietnameseExample: 'Thêm hành tây khi nấu ăn làm món ăn ngon hơn.',
  },
  {
    word: '마늘',
    topic: 'Rau củ',
    hint: 'Tỏi, gia vị quan trọng trong ẩm thực Hàn Quốc',
    koreanExample: '한국 요리에는 마늘을 많이 사용해요.',
    vietnameseExample: 'Tỏi được sử dụng nhiều trong ẩm thực Hàn Quốc.',
  },
  {
    word: '오이',
    topic: 'Rau củ',
    hint: 'Dưa chuột, thường ăn sống hoặc làm kimchi',
    koreanExample: '오이는 시원하고 아삭아삭해요.',
    vietnameseExample: 'Dưa chuột mát và giòn.',
  },
  {
    word: '가지',
    topic: 'Rau củ',
    hint: 'Cà tím, thường được nướng hoặc xào',
    koreanExample: '가지를 구워서 먹으면 맛있어요.',
    vietnameseExample: 'Cà tím nướng rất ngon.',
  },
  {
    word: '토마토',
    topic: 'Rau củ',
    hint: 'Cà chua, có thể ăn sống hoặc nấu chín',
    koreanExample: '토마토는 비타민이 풍부해요.',
    vietnameseExample: 'Cà chua giàu vitamin.',
  },
  {
    word: '고추',
    topic: 'Rau củ',
    hint: 'Ớt, thành phần quan trọng trong nhiều món ăn cay của Hàn Quốc',
    koreanExample: '고추는 한국 요리에서 매운맛을 내는 데 중요해요.',
    vietnameseExample:
      'Ớt là thành phần quan trọng tạo vị cay trong món ăn Hàn Quốc.',
  },
  {
    word: '파',
    topic: 'Rau củ',
    hint: 'Hành lá, thường được dùng làm gia vị hoặc garnish',
    koreanExample: '파는 국이나 찌개에 넣으면 향이 좋아요.',
    vietnameseExample: 'Hành lá tạo hương thơm khi cho vào canh hoặc soup.',
  },
  {
    word: '상추',
    topic: 'Rau củ',
    hint: 'Rau xà lách, thường dùng để gói thịt nướng',
    koreanExample: '삼겹살을 상추에 싸서 먹어요.',
    vietnameseExample:
      'Chúng tôi gói thịt ba chỉ nướng bằng rau xà lách để ăn.',
  },
  {
    word: '시금치',
    topic: 'Rau củ',
    hint: 'Rau chân vịt (rau bina), giàu sắt và vitamin',
    koreanExample: '시금치는 철분이 풍부한 채소예요.',
    vietnameseExample: 'Rau chân vịt là loại rau giàu sắt.',
  },
  {
    word: '버섯',
    topic: 'Rau củ',
    hint: 'Nấm, có nhiều loại khác nhau được sử dụng trong ẩm thực Hàn Quốc',
    koreanExample: '버섯은 다양한 종류가 있고 요리에 많이 사용돼요.',
    vietnameseExample: 'Có nhiều loại nấm khác nhau được sử dụng trong nấu ăn.',
  },
  {
    word: '콩나물',
    topic: 'Rau củ',
    hint: 'Giá đỗ, thường dùng trong canh hoặc xào',
    koreanExample: '콩나물국은 해장에 좋아요.',
    vietnameseExample: 'Canh giá đỗ rất tốt để giải rượu.',
  },
  {
    word: '호박',
    topic: 'Rau củ',
    hint: 'Bí ngô, có thể nấu canh hoặc hầm',
    koreanExample: '호박은 단맛이 나고 영양가가 높아요.',
    vietnameseExample: 'Bí ngô có vị ngọt và giá trị dinh dưỡng cao.',
  },
  {
    word: '브로콜리',
    topic: 'Rau củ',
    hint: 'Bông cải xanh, giàu vitamin và khoáng chất',
    koreanExample: '브로콜리는 건강에 좋은 채소예요.',
    vietnameseExample: 'Bông cải xanh là loại rau tốt cho sức khỏe.',
  },
  {
    word: '양배추',
    topic: 'Rau củ',
    hint: 'Bắp cải tròn, thường dùng trong salad hoặc xào',
    koreanExample: '양배추는 샐러드로 많이 먹어요.',
    vietnameseExample: 'Bắp cải thường được ăn như salad.',
  },
  {
    word: '피망',
    topic: 'Rau củ',
    hint: 'Ớt chuông, thường có màu xanh, đỏ hoặc vàng',
    koreanExample: '피망은 색깔이 다양하고 비타민이 풍부해요.',
    vietnameseExample: 'Ớt chuông có nhiều màu sắc khác nhau và giàu vitamin.',
  },
  {
    word: '아르바이트',
    topic: 'Công việc',
    hint: 'Việc làm thêm, bán thời gian',
    koreanExample: '학생들은 주말에 아르바이트를 많이 해요.',
    vietnameseExample: 'Sinh viên thường làm thêm vào cuối tuần.',
  },
  {
    word: '통역',
    topic: 'Công việc',
    hint: 'Phiên dịch, dịch nói từ một ngôn ngữ sang ngôn ngữ khác',
    koreanExample: '그녀는 국제 회의에서 통역을 담당했어요.',
    vietnameseExample: 'Cô ấy phụ trách phiên dịch tại hội nghị quốc tế.',
  },
  {
    word: '번역',
    topic: 'Công việc',
    hint: 'Biên dịch, dịch viết từ một ngôn ngữ sang ngôn ngữ khác',
    koreanExample: '그는 한국어 소설을 베트남어로 번역하고 있어요.',
    vietnameseExample:
      'Anh ấy đang dịch tiểu thuyết tiếng Hàn sang tiếng Việt.',
  },
  {
    word: '취업',
    topic: 'Công việc',
    hint: 'Tìm được việc làm, được tuyển dụng',
    koreanExample: '대학 졸업 후에 취업을 준비하고 있어요.',
    vietnameseExample: 'Tôi đang chuẩn bị tìm việc sau khi tốt nghiệp đại học.',
  },
  {
    word: '면접',
    topic: 'Công việc',
    hint: 'Phỏng vấn xin việc',
    koreanExample: '내일 큰 회사에서 면접이 있어요.',
    vietnameseExample: 'Ngày mai tôi có buổi phỏng vấn tại một công ty lớn.',
  },
  {
    word: '이력서',
    topic: 'Công việc',
    hint: 'Sơ yếu lý lịch, CV',
    koreanExample: '이력서를 여러 회사에 보냈어요.',
    vietnameseExample: 'Tôi đã gửi CV đến nhiều công ty.',
  },
  {
    word: '급여',
    topic: 'Công việc',
    hint: 'Tiền lương, tiền công',
    koreanExample: '이 회사는 급여가 높은 편이에요.',
    vietnameseExample: 'Công ty này có mức lương khá cao.',
  },
  {
    word: '계약직',
    topic: 'Công việc',
    hint: 'Nhân viên hợp đồng, việc làm có thời hạn',
    koreanExample: '그는 1년 계약직으로 일하고 있어요.',
    vietnameseExample: 'Anh ấy đang làm việc theo hợp đồng 1 năm.',
  },
  {
    word: '정규직',
    topic: 'Công việc',
    hint: 'Nhân viên chính thức, việc làm toàn thời gian',
    koreanExample: '계약직에서 정규직으로 전환되었어요.',
    vietnameseExample:
      'Tôi đã được chuyển từ nhân viên hợp đồng sang nhân viên chính thức.',
  },
  {
    word: '퇴근',
    topic: 'Công việc',
    hint: 'Tan làm, kết thúc giờ làm việc',
    koreanExample: '보통 6시에 퇴근해요.',
    vietnameseExample: 'Tôi thường tan làm lúc 6 giờ.',
  },
  {
    word: '출근',
    topic: 'Công việc',
    hint: 'Đi làm, bắt đầu giờ làm việc',
    koreanExample: '매일 아침 9시에 출근해요.',
    vietnameseExample: 'Tôi đi làm lúc 9 giờ sáng mỗi ngày.',
  },
  {
    word: '야근',
    topic: 'Công việc',
    hint: 'Làm thêm giờ, làm việc muộn',
    koreanExample: '이번 주에는 프로젝트 때문에 야근을 많이 했어요.',
    vietnameseExample: 'Tuần này tôi đã làm thêm giờ nhiều vì dự án.',
  },
  {
    word: '연봉',
    topic: 'Công việc',
    hint: 'Lương hàng năm',
    koreanExample: '이 직업의 평균 연봉은 얼마예요?',
    vietnameseExample:
      'Mức lương trung bình hàng năm của nghề này là bao nhiêu?',
  },
  {
    word: '휴가',
    topic: 'Công việc',
    hint: 'Kỳ nghỉ, ngày nghỉ phép',
    koreanExample: '다음 달에 휴가를 낼 예정이에요.',
    vietnameseExample: 'Tôi dự định xin nghỉ phép vào tháng sau.',
  },
  {
    word: '재택근무',
    topic: 'Công việc',
    hint: 'Làm việc tại nhà',
    koreanExample: '요즘에는 재택근무를 하는 회사가 많아졌어요.',
    vietnameseExample: 'Gần đây, nhiều công ty cho phép làm việc tại nhà.',
  },
  {
    word: '시간제',
    topic: 'Công việc',
    hint: 'Công việc bán thời gian, theo giờ',
    koreanExample: '학생들은 주로 시간제로 일해요.',
    vietnameseExample: 'Sinh viên thường làm việc bán thời gian.',
  },
  {
    word: '인턴',
    topic: 'Công việc',
    hint: 'Thực tập sinh',
    koreanExample: '여름방학 동안 대기업에서 인턴으로 일했어요.',
    vietnameseExample:
      'Tôi đã làm thực tập sinh tại một công ty lớn trong kỳ nghỉ hè.',
  },
  {
    word: '구직',
    topic: 'Công việc',
    hint: 'Tìm việc làm',
    koreanExample: '요즘 구직 활동을 열심히 하고 있어요.',
    vietnameseExample: 'Gần đây tôi đang tích cực tìm việc làm.',
  },
  {
    word: '승진',
    topic: 'Công việc',
    hint: 'Thăng chức, lên chức',
    koreanExample: '그는 열심히 일한 결과로 승진했어요.',
    vietnameseExample: 'Anh ấy đã được thăng chức nhờ làm việc chăm chỉ.',
  },
  {
    word: '퇴사',
    topic: 'Công việc',
    hint: 'Nghỉ việc, rời khỏi công ty',
    koreanExample: '그녀는 새로운 기회를 위해 퇴사했어요.',
    vietnameseExample: 'Cô ấy đã nghỉ việc để tìm kiếm cơ hội mới.',
  },
  {
    word: '직원',
    topic: 'Chức danh và xưng hô',
    hint: 'Nhân viên, người làm việc trong một tổ chức hoặc công ty',
    koreanExample: '우리 회사의 직원 수는 약 100명입니다.',
    vietnameseExample:
      'Số lượng nhân viên của công ty chúng tôi là khoảng 100 người.',
  },
  {
    word: '팀장',
    topic: 'Chức danh và xưng hô',
    hint: 'Trưởng nhóm, người phụ trách một nhóm nhỏ trong công ty',
    koreanExample: '팀장님께서 업무를 배분해 주셨습니다.',
    vietnameseExample: 'Trưởng nhóm đã phân chia công việc cho chúng tôi.',
  },
  {
    word: '실장',
    topic: 'Chức danh và xưng hô',
    hint: 'Trưởng phòng, người đứng đầu một phòng hoặc bộ phận',
    koreanExample: '마케팅 실장이 새로운 전략을 제안했습니다.',
    vietnameseExample: 'Trưởng phòng tiếp thị đã đề xuất chiến lược mới.',
  },
  {
    word: '사장',
    topic: 'Chức danh và xưng hô',
    hint: 'Giám đốc, cách gọi tôn trọng dành cho người đứng đầu công ty',
    koreanExample: '사장님께서 회의에 참석하셨습니다.',
    vietnameseExample: 'Giám đốc đã tham dự cuộc họp.',
  },
  {
    word: '부장',
    topic: 'Chức danh và xưng hô',
    hint: 'Trưởng phòng, chức vụ quản lý cấp cao trong công ty',
    koreanExample: '김 부장은 마케팅 부서를 담당합니다.',
    vietnameseExample: 'Trưởng phòng Kim phụ trách bộ phận tiếp thị.',
  },
  {
    word: '과장',
    topic: 'Chức danh và xưng hô',
    hint: 'Trưởng nhóm, chức vụ quản lý cấp trung trong công ty',
    koreanExample: '이 과장은 프로젝트 관리를 맡고 있어요.',
    vietnameseExample: 'Trưởng nhóm Lee đang phụ trách quản lý dự án.',
  },
  {
    word: '대리',
    topic: 'Chức danh và xưng hô',
    hint: 'Đại diện, chức vụ cấp dưới trưởng nhóm trong công ty',
    koreanExample: '박 대리가 이번 발표를 준비했습니다.',
    vietnameseExample: 'Đại diện Park đã chuẩn bị bài thuyết trình này.',
  },
  {
    word: '사원',
    topic: 'Chức danh và xưng hô',
    hint: 'Nhân viên, vị trí thấp nhất trong hệ thống cấp bậc công ty',
    koreanExample: '신입 사원이 오늘부터 일을 시작합니다.',
    vietnameseExample: 'Nhân viên mới bắt đầu làm việc từ hôm nay.',
  },
  {
    word: '괜찮아',
    topic: 'Âm nhạc Việt Nam, V-pop',
    hint: 'KHÔNG SAO CẢ - 7dnight',
    koreanExample: "그 베트남 노래 '괜찮아'는 매우 인기가 있어요.",
    vietnameseExample: "Bài hát Việt Nam 'KHÔNG SAO CẢ' rất nổi tiếng.",
  },
  {
    word: '식당',
    topic: 'Địa điểm',
    hint: 'Nhà hàng, nơi ăn uống',
    koreanExample: '이 근처에 맛있는 식당이 많아요.',
    vietnameseExample: 'Có nhiều nhà hàng ngon gần đây.',
  },
  {
    word: '카페',
    topic: 'Địa điểm',
    hint: 'Quán cà phê',
    koreanExample: '친구와 카페에서 만났어요.',
    vietnameseExample: 'Tôi đã gặp bạn tại quán cà phê.',
  },
  {
    word: '분식집',
    topic: 'Địa điểm',
    hint: 'Quán ăn vặt Hàn Quốc, bán tteokbokki, mandu, v.v.',
    koreanExample: '학교 앞 분식집에서 떡볶이를 먹었어요.',
    vietnameseExample: 'Tôi đã ăn tteokbokki tại quán ăn vặt trước trường.',
  },
  {
    word: '패스트푸드점',
    topic: 'Địa điểm',
    hint: 'Cửa hàng đồ ăn nhanh',
    koreanExample: '패스트푸드점에서 햄버거를 주문했어요.',
    vietnameseExample: 'Tôi đã đặt hamburger tại cửa hàng đồ ăn nhanh.',
  },
  {
    word: '편의점',
    topic: 'Địa điểm',
    hint: 'Cửa hàng tiện lợi',
    koreanExample: '편의점에서 라면을 사왔어요.',
    vietnameseExample: 'Tôi đã mua mì ăn liền từ cửa hàng tiện lợi.',
  },
  {
    word: '베이커리',
    topic: 'Địa điểm',
    hint: 'Tiệm bánh',
    koreanExample: '베이커리에서 빵을 샀어요.',
    vietnameseExample: 'Tôi đã mua bánh mì từ tiệm bánh.',
  },
  {
    word: '치킨집',
    topic: 'Địa điểm',
    hint: 'Quán gà rán',
    koreanExample: '친구들과 치킨집에서 맥주와 치킨을 먹었어요.',
    vietnameseExample:
      'Tôi đã ăn gà rán và uống bia với bạn bè tại quán gà rán.',
  },
  {
    word: '고기집',
    topic: 'Địa điểm',
    hint: 'Nhà hàng thịt nướng',
    koreanExample: '주말에 가족과 고기집에 갔어요.',
    vietnameseExample: 'Cuối tuần tôi đã đến nhà hàng thịt nướng với gia đình.',
  },
  {
    word: '한식당',
    topic: 'Địa điểm',
    hint: 'Nhà hàng đồ ăn Hàn Quốc',
    koreanExample: '외국인 친구에게 한식당을 소개해 주었어요.',
    vietnameseExample: 'Tôi đã giới thiệu nhà hàng đồ Hàn cho bạn nước ngoài.',
  },
  {
    word: '일식집',
    topic: 'Địa điểm',
    hint: 'Nhà hàng đồ ăn Nhật Bản',
    koreanExample: '일식집에서 초밥을 먹었어요.',
    vietnameseExample: 'Tôi đã ăn sushi tại nhà hàng Nhật Bản.',
  },
  {
    word: '중국집',
    topic: 'Địa điểm',
    hint: 'Nhà hàng đồ ăn Trung Quốc',
    koreanExample: '중국집에서 짜장면을 배달시켰어요.',
    vietnameseExample: 'Tôi đã đặt mì đen giao hàng từ nhà hàng Trung Quốc.',
  },
  {
    word: '분식점',
    topic: 'Địa điểm',
    hint: 'Quán ăn vặt Hàn Quốc',
    koreanExample: '방과 후에 분식점에 가서 라볶이를 먹었어요.',
    vietnameseExample: 'Sau giờ học, tôi đã đến quán ăn vặt để ăn rabokki.',
  },

  // 술집/유흥 관련 장소
  {
    word: '술집',
    topic: 'Địa điểm',
    hint: 'Quán rượu, quán bar',
    koreanExample: '친구들과 술집에서 소주를 마셨어요.',
    vietnameseExample: 'Tôi đã uống soju với bạn bè tại quán rượu.',
  },
  {
    word: '호프집',
    topic: 'Địa điểm',
    hint: 'Quán bia, quán nhậu',
    koreanExample: '회사 동료들과 호프집에서 회식을 했어요.',
    vietnameseExample: 'Tôi đã ăn tối với đồng nghiệp tại quán bia.',
  },
  {
    word: '주점',
    topic: 'Địa điểm',
    hint: 'Quán rượu truyền thống',
    koreanExample: '한국 전통 주점에서 막걸리를 마셨어요.',
    vietnameseExample:
      'Tôi đã uống makgeolli tại quán rượu truyền thống của Hàn Quốc.',
  },
  {
    word: '바',
    topic: 'Địa điểm',
    hint: 'Quán bar',
    koreanExample: '강남의 유명한 바에 가 보고 싶어요.',
    vietnameseExample: 'Tôi muốn đến thăm một quán bar nổi tiếng ở Gangnam.',
  },
  {
    word: '클럽',
    topic: 'Địa điểm',
    hint: 'Câu lạc bộ đêm, vũ trường',
    koreanExample: '주말에 친구들과 클럽에 갔어요.',
    vietnameseExample: 'Cuối tuần tôi đã đi câu lạc bộ đêm với bạn bè.',
  },
  {
    word: '노래방',
    topic: 'Địa điểm',
    hint: 'Phòng karaoke',
    koreanExample: '친구의 생일을 축하하기 위해 노래방에 갔어요.',
    vietnameseExample:
      'Tôi đã đến phòng karaoke để chúc mừng sinh nhật bạn tôi.',
  },
  {
    word: '가라오케',
    topic: 'Địa điểm',
    hint: 'Karaoke',
    koreanExample: '직장 동료들과 가라오케에서 노래를 불렀어요.',
    vietnameseExample: 'Tôi đã hát karaoke với đồng nghiệp.',
  },

  // 공원/여가/관광 관련 장소
  {
    word: '공원',
    topic: 'Địa điểm',
    hint: 'Công viên',
    koreanExample: '주말에 공원에서 산책했어요.',
    vietnameseExample: 'Tôi đã đi dạo trong công viên vào cuối tuần.',
  },
  {
    word: '놀이공원',
    topic: 'Địa điểm',
    hint: 'Công viên giải trí',
    koreanExample: '어린이날에 놀이공원에 갔어요.',
    vietnameseExample: 'Tôi đã đến công viên giải trí vào Ngày Thiếu nhi.',
  },
  {
    word: '영화관',
    topic: 'Địa điểm',
    hint: 'Rạp chiếu phim',
    koreanExample: '주말에 친구와 영화관에서 영화를 봤어요.',
    vietnameseExample: 'Cuối tuần tôi đã xem phim tại rạp với bạn.',
  },
  {
    word: '박물관',
    topic: 'Địa điểm',
    hint: 'Bảo tàng',
    koreanExample: '박물관에서 한국 역사에 대해 배웠어요.',
    vietnameseExample: 'Tôi đã học về lịch sử Hàn Quốc tại bảo tàng.',
  },
  {
    word: '미술관',
    topic: 'Địa điểm',
    hint: 'Viện bảo tàng nghệ thuật',
    koreanExample: '현대 미술관에서 전시회를 관람했어요.',
    vietnameseExample:
      'Tôi đã tham quan triển lãm tại viện bảo tàng nghệ thuật hiện đại.',
  },
  {
    word: '동물원',
    topic: 'Địa điểm',
    hint: 'Vườn thú',
    koreanExample: '아이들과 함께 동물원에 갔어요.',
    vietnameseExample: 'Tôi đã đến vườn thú cùng với trẻ em.',
  },
  {
    word: '수족관',
    topic: 'Địa điểm',
    hint: 'Thủy cung',
    koreanExample: '부산 수족관에서 다양한 물고기를 보았어요.',
    vietnameseExample: 'Tôi đã nhìn thấy nhiều loại cá tại thủy cung Busan.',
  },
  {
    word: '식물원',
    topic: 'Địa điểm',
    hint: 'Vườn thực vật',
    koreanExample: '식물원에서 희귀한 식물들을 구경했어요.',
    vietnameseExample:
      'Tôi đã xem những loài thực vật quý hiếm tại vườn thực vật.',
  },
  {
    word: '유원지',
    topic: 'Địa điểm',
    hint: 'Khu vui chơi giải trí',
    koreanExample: '가족들과 유원지에서 하루를 보냈어요.',
    vietnameseExample:
      'Tôi đã dành một ngày ở khu vui chơi giải trí với gia đình.',
  },

  // 교통/이동 관련 장소
  {
    word: '주차장',
    topic: 'Địa điểm',
    hint: 'Bãi đỗ xe',
    koreanExample: '백화점 주차장에 차를 주차했어요.',
    vietnameseExample: 'Tôi đã đỗ xe ở bãi đỗ xe của trung tâm mua sắm.',
  },
  {
    word: '지하철역',
    topic: 'Địa điểm',
    hint: 'Ga tàu điện ngầm',
    koreanExample: '지하철역에서 친구를 만났어요.',
    vietnameseExample: 'Tôi đã gặp bạn tại ga tàu điện ngầm.',
  },
  {
    word: '버스정류장',
    topic: 'Địa điểm',
    hint: 'Trạm xe buýt',
    koreanExample: '버스정류장에서 버스를 기다렸어요.',
    vietnameseExample: 'Tôi đã đợi xe buýt tại trạm xe buýt.',
  },
  {
    word: '공항',
    topic: 'Địa điểm',
    hint: 'Sân bay',
    koreanExample: '인천 공항에서 비행기를 탔어요.',
    vietnameseExample: 'Tôi đã lên máy bay tại sân bay Incheon.',
  },
  {
    word: '기차역',
    topic: 'Địa điểm',
    hint: 'Ga tàu hỏa',
    koreanExample: '서울역에서 부산행 KTX를 탔어요.',
    vietnameseExample: 'Tôi đã đi tàu KTX đến Busan từ ga Seoul.',
  },
  {
    word: '터미널',
    topic: 'Địa điểm',
    hint: 'Bến xe khách',
    koreanExample: '고속버스 터미널에서 고향으로 가는 버스를 탔어요.',
    vietnameseExample: 'Tôi đã bắt xe buýt về quê từ bến xe buýt cao tốc.',
  },

  // 공공 시설/일상 장소
  {
    word: '도서관',
    topic: 'Địa điểm',
    hint: 'Thư viện',
    koreanExample: '시험 공부를 위해 도서관에 갔어요.',
    vietnameseExample: 'Tôi đã đến thư viện để học thi.',
  },
  {
    word: '학교',
    topic: 'Địa điểm',
    hint: 'Trường học',
    koreanExample: '매일 아침 8시에 학교에 가요.',
    vietnameseExample: 'Tôi đi học vào 8 giờ sáng mỗi ngày.',
  },
  {
    word: '병원',
    topic: 'Địa điểm',
    hint: 'Bệnh viện',
    koreanExample: '감기에 걸려서 병원에 갔어요.',
    vietnameseExample: 'Tôi đã đến bệnh viện vì bị cảm lạnh.',
  },
  {
    word: '약국',
    topic: 'Địa điểm',
    hint: 'Hiệu thuốc',
    koreanExample: '두통약을 사러 약국에 갔어요.',
    vietnameseExample: 'Tôi đã đến hiệu thuốc để mua thuốc đau đầu.',
  },
  {
    word: '은행',
    topic: 'Địa điểm',
    hint: 'Ngân hàng',
    koreanExample: '계좌를 개설하기 위해 은행에 갔어요.',
    vietnameseExample: 'Tôi đã đến ngân hàng để mở tài khoản.',
  },
  {
    word: '우체국',
    topic: 'Địa điểm',
    hint: 'Bưu điện',
    koreanExample: '소포를 보내기 위해 우체국에 갔어요.',
    vietnameseExample: 'Tôi đã đến bưu điện để gửi bưu kiện.',
  },
  {
    word: '경찰서',
    topic: 'Địa điểm',
    hint: 'Đồn cảnh sát',
    koreanExample: '분실물을 신고하러 경찰서에 갔어요.',
    vietnameseExample: 'Tôi đã đến đồn cảnh sát để báo cáo đồ bị mất.',
  },
  {
    word: '시청',
    topic: 'Địa điểm',
    hint: 'Tòa thị chính',
    koreanExample: '외국인 등록증을 받기 위해 시청에 갔어요.',
    vietnameseExample:
      'Tôi đã đến tòa thị chính để nhận thẻ đăng ký người nước ngoài.',
  },
  {
    word: '헬스장',
    topic: 'Địa điểm',
    hint: 'Phòng tập thể dục',
    koreanExample: '매일 저녁 헬스장에서 운동해요.',
    vietnameseExample: 'Tôi tập thể dục ở phòng tập mỗi tối.',
  },
  {
    word: '미용실',
    topic: 'Địa điểm',
    hint: 'Tiệm làm tóc',
    koreanExample: '머리를 자르러 미용실에 갔어요.',
    vietnameseExample: 'Tôi đã đến tiệm làm tóc để cắt tóc.',
  },
  {
    word: '목욕탕',
    topic: 'Địa điểm',
    hint: 'Nhà tắm công cộng',
    koreanExample: '주말에 가족과 함께 목욕탕에 갔어요.',
    vietnameseExample: 'Cuối tuần tôi đã đến nhà tắm công cộng với gia đình.',
  },
  {
    word: '백화점',
    topic: 'Địa điểm',
    hint: 'Trung tâm mua sắm, cửa hàng bách hóa',
    koreanExample: '선물을 사기 위해 백화점에 갔어요.',
    vietnameseExample: 'Tôi đã đến trung tâm mua sắm để mua quà.',
  },
  {
    word: '마트',
    topic: 'Địa điểm',
    hint: 'Siêu thị',
    koreanExample: '주말에 마트에서 장을 봤어요.',
    vietnameseExample: 'Tôi đã đi mua sắm tại siêu thị vào cuối tuần.',
  },
  {
    word: '시장',
    topic: 'Địa điểm',
    hint: 'Chợ',
    koreanExample: '신선한 야채를 사러 시장에 갔어요.',
    vietnameseExample: 'Tôi đã đến chợ để mua rau tươi.',
  },
  {
    word: '어린이집',
    topic: 'Địa điểm',
    hint: 'Nhà trẻ',
    koreanExample: '아이를 어린이집에 맡겼어요.',
    vietnameseExample: 'Tôi đã gửi con tại nhà trẻ.',
  },
  {
    word: '사무실',
    topic: 'Địa điểm',
    hint: 'Văn phòng',
    koreanExample: '매일 9시에 사무실에 출근해요.',
    vietnameseExample: 'Tôi đi làm tại văn phòng lúc 9 giờ mỗi ngày.',
  },
  {
    word: '체육관',
    topic: 'Địa điểm',
    hint: 'Nhà thi đấu thể thao',
    koreanExample: '농구 경기를 보러 체육관에 갔어요.',
    vietnameseExample: 'Tôi đã đến nhà thi đấu để xem trận bóng rổ.',
  },
  {
    word: '자동차',
    topic: 'Phương tiện giao thông',
    hint: 'Ô tô, phương tiện có bốn bánh phổ biến',
    koreanExample: '자동차를 타고 여행을 갔어요.',
    vietnameseExample: 'Tôi đã đi du lịch bằng ô tô.',
  },
  {
    word: '버스',
    topic: 'Phương tiện giao thông',
    hint: 'Xe buýt, phương tiện công cộng chở nhiều người',
    koreanExample: '매일 버스를 타고 학교에 가요.',
    vietnameseExample: 'Tôi đi học bằng xe buýt mỗi ngày.',
  },
  {
    word: '지하철',
    topic: 'Phương tiện giao thông',
    hint: 'Tàu điện ngầm, phương tiện chạy dưới lòng đất',
    koreanExample: '서울에서는 지하철이 가장 편리해요.',
    vietnameseExample: 'Ở Seoul, tàu điện ngầm là phương tiện thuận tiện nhất.',
  },
  {
    word: '기차',
    topic: 'Phương tiện giao thông',
    hint: 'Tàu hỏa, phương tiện chạy trên đường ray',
    koreanExample: '기차를 타고 부산에 갔어요.',
    vietnameseExample: 'Tôi đã đi Busan bằng tàu hỏa.',
  },
  {
    word: '택시',
    topic: 'Phương tiện giao thông',
    hint: 'Taxi, phương tiện có tính phí theo quãng đường',
    koreanExample: '늦어서 택시를 탔어요.',
    vietnameseExample: 'Tôi đã đi taxi vì bị muộn.',
  },
  {
    word: '비행기',
    topic: 'Phương tiện giao thông',
    hint: 'Máy bay, phương tiện bay trên không trung',
    koreanExample: '비행기를 타고 베트남에 갔어요.',
    vietnameseExample: 'Tôi đã đi Việt Nam bằng máy bay.',
  },
  {
    word: '배',
    topic: 'Phương tiện giao thông',
    hint: 'Tàu thủy, thuyền, phương tiện đi trên nước',
    koreanExample: '제주도까지 배로 여행했어요.',
    vietnameseExample: 'Tôi đã đi du lịch đến đảo Jeju bằng tàu.',
  },
  {
    word: '자전거',
    topic: 'Phương tiện giao thông',
    hint: 'Xe đạp, phương tiện hai bánh đạp bằng chân',
    koreanExample: '주말에 자전거를 타고 공원에 갔어요.',
    vietnameseExample: 'Cuối tuần tôi đã đi công viên bằng xe đạp.',
  },
  {
    word: '오토바이',
    topic: 'Phương tiện giao thông',
    hint: 'Xe máy, phương tiện hai bánh có động cơ',
    koreanExample: '베트남에서는 오토바이를 많이 타요.',
    vietnameseExample: 'Ở Việt Nam, người ta thường đi xe máy nhiều.',
  },
  {
    word: '트럭',
    topic: 'Phương tiện giao thông',
    hint: 'Xe tải, phương tiện chở hàng hóa',
    koreanExample: '이사할 때 트럭을 불렀어요.',
    vietnameseExample: 'Tôi đã gọi xe tải khi chuyển nhà.',
  },
  {
    word: '헬리콥터',
    topic: 'Phương tiện giao thông',
    hint: 'Máy bay trực thăng, phương tiện bay có cánh quạt',
    koreanExample: '응급 환자를 헬리콥터로 이송했어요.',
    vietnameseExample:
      'Bệnh nhân khẩn cấp đã được vận chuyển bằng máy bay trực thăng.',
  },
  {
    word: '전철',
    topic: 'Phương tiện giao thông',
    hint: 'Tàu điện đô thị, giống tàu điện ngầm nhưng có thể chạy trên mặt đất',
    koreanExample: '전철을 타고 시내에 갔어요.',
    vietnameseExample:
      'Tôi đã đi vào trung tâm thành phố bằng tàu điện đô thị.',
  },
  {
    word: '킥보드',
    topic: 'Phương tiện giao thông',
    hint: 'Xe scooter, phương tiện nhỏ đứng một chân và đẩy',
    koreanExample: '요즘 전동 킥보드가 인기가 많아요.',
    vietnameseExample: 'Xe scooter điện rất phổ biến gần đây.',
  },
  {
    word: '케이블카',
    topic: 'Phương tiện giao thông',
    hint: 'Cáp treo, phương tiện di chuyển trên không bằng dây cáp',
    koreanExample: '산에서 케이블카를 타고 정상에 올라갔어요.',
    vietnameseExample: 'Tôi đã lên đỉnh núi bằng cáp treo.',
  },
  {
    word: '페리',
    topic: 'Phương tiện giao thông',
    hint: 'Phà, tàu chở người và xe cộ qua sông hoặc biển',
    koreanExample: '섬으로 가기 위해 페리를 탔어요.',
    vietnameseExample: 'Tôi đã đi phà để đến đảo.',
  },
  {
    word: '구급차',
    topic: 'Phương tiện giao thông',
    hint: 'Xe cứu thương, xe chở người bị thương đến bệnh viện',
    koreanExample: '사고가 나서 구급차가 왔어요.',
    vietnameseExample: 'Xe cứu thương đã đến sau khi xảy ra tai nạn.',
  },
  {
    word: '스쿠터',
    topic: 'Phương tiện giao thông',
    hint: 'Xe scooter, loại xe máy nhỏ',
    koreanExample: '여름에는 스쿠터를 타고 출근해요.',
    vietnameseExample: 'Vào mùa hè, tôi đi làm bằng xe scooter.',
  },
  {
    word: '요트',
    topic: 'Phương tiện giao thông',
    hint: 'Du thuyền, tàu dùng để giải trí',
    koreanExample: '휴가 때 요트를 빌려서 바다에 나갔어요.',
    vietnameseExample: 'Trong kỳ nghỉ, tôi đã thuê du thuyền và ra biển.',
  },
  {
    word: '리무진',
    topic: 'Phương tiện giao thông',
    hint: 'Xe limousine, xe sang trọng thường dùng trong dịp đặc biệt',
    koreanExample: '결혼식에 리무진을 대절했어요.',
    vietnameseExample: 'Chúng tôi đã thuê xe limousine cho đám cưới.',
  },
  {
    word: '독서',
    topic: 'Sở thích',
    hint: 'Đọc sách, hoạt động đọc để giải trí hoặc học tập',
    koreanExample: '저는 취미로 독서를 즐겨요.',
    vietnameseExample: 'Tôi thích đọc sách như một sở thích.',
  },
  {
    word: '음악감상',
    topic: 'Sở thích',
    hint: 'Nghe nhạc, thưởng thức âm nhạc',
    koreanExample: '퇴근 후에 음악 감상을 해요.',
    vietnameseExample: 'Tôi nghe nhạc sau khi tan làm.',
  },
  {
    word: '영화감상',
    topic: 'Sở thích',
    hint: 'Xem phim, thưởng thức phim ảnh',
    koreanExample: '주말에는 보통 영화 감상을(보기를) 즐겨요.',
    vietnameseExample: 'Tôi thường thích xem phim vào cuối tuần.',
  },
  {
    word: '요리',
    topic: 'Sở thích',
    hint: 'Nấu ăn, chuẩn bị món ăn',
    koreanExample: '요리가 제 취미 중 하나예요.',
    vietnameseExample: 'Nấu ăn là một trong những sở thích của tôi.',
  },
  {
    word: '여행',
    topic: 'Sở thích',
    hint: 'Du lịch, đi đến các địa điểm khác nhau',
    koreanExample: '여행을 통해 새로운 문화를 경험해요.',
    vietnameseExample: 'Tôi trải nghiệm các nền văn hóa mới thông qua du lịch.',
  },
  {
    word: '등산',
    topic: 'Sở thích',
    hint: 'Leo núi, đi bộ lên núi',
    koreanExample: '주말마다 등산을 하러 가요.',
    vietnameseExample: 'Tôi đi leo núi mỗi cuối tuần.',
  },
  {
    word: '낚시',
    topic: 'Sở thích',
    hint: 'Câu cá, hoạt động bắt cá bằng cần câu',
    koreanExample: '아버지와 함께 낚시를 하러 갔어요.',
    vietnameseExample: 'Tôi đã đi câu cá cùng bố tôi.',
  },
  {
    word: '사진 찍기',
    topic: 'Sở thích',
    hint: 'Chụp ảnh, ghi lại khoảnh khắc bằng máy ảnh',
    koreanExample: '사진 찍기가 제 취미예요.',
    vietnameseExample: 'Chụp ảnh là sở thích của tôi.',
  },
  {
    word: '그림 그리기',
    topic: 'Sở thích',
    hint: 'Vẽ tranh, tạo ra hình ảnh bằng bút, cọ',
    koreanExample: '주말에 그림 그리기를 배우고 있어요.',
    vietnameseExample: 'Tôi đang học vẽ tranh vào cuối tuần.',
  },
  {
    word: '수영',
    topic: 'Sở thích',
    hint: 'Bơi lội, hoạt động thể thao dưới nước',
    koreanExample: '여름에는 매일 수영을 해요.',
    vietnameseExample: 'Vào mùa hè, tôi bơi mỗi ngày.',
  },
  {
    word: '축구',
    topic: 'Sở thích',
    hint: 'Bóng đá, môn thể thao đá bóng',
    koreanExample: '친구들과 주말마다 축구를 해요.',
    vietnameseExample: 'Tôi chơi bóng đá với bạn bè mỗi cuối tuần.',
  },
  {
    word: '농구',
    topic: 'Sở thích',
    hint: 'Bóng rổ, môn thể thao ném bóng vào rổ',
    koreanExample: '학교에서 농구 동아리 활동을 해요.',
    vietnameseExample: 'Tôi tham gia câu lạc bộ bóng rổ ở trường.',
  },
  {
    word: '골프',
    topic: 'Sở thích',
    hint: 'Golf, môn thể thao đánh bóng vào lỗ',
    koreanExample: '주말에 친구들과 골프를 치러 가요.',
    vietnameseExample: 'Cuối tuần tôi đi chơi golf với bạn bè.',
  },
  {
    word: '댄스',
    topic: 'Sở thích',
    hint: 'Nhảy múa, nghệ thuật chuyển động theo nhạc',
    koreanExample: 'K-pop 댄스를 배우고 있어요.',
    vietnameseExample: 'Tôi đang học nhảy K-pop.',
  },
  {
    word: '원예',
    topic: 'Sở thích',
    hint: 'Làm vườn, trồng và chăm sóc cây',
    koreanExample: '주말에 원예를 즐겨요.',
    vietnameseExample: 'Tôi thích làm vườn vào cuối tuần.',
  },
  {
    word: '뜨개질',
    topic: 'Sở thích',
    hint: 'Đan len, tạo ra đồ bằng len và kim đan',
    koreanExample: '겨울에는 뜨개질로 목도리를 만들어요.',
    vietnameseExample: 'Vào mùa đông, tôi đan khăn quàng cổ.',
  },
  {
    word: '수집',
    topic: 'Sở thích',
    hint: 'Sưu tầm, thu thập các đồ vật theo chủ đề',
    koreanExample: '우표 수집이 제 취미예요.',
    vietnameseExample: 'Sưu tầm tem là sở thích của tôi.',
  },
  {
    word: '게임',
    topic: 'Sở thích',
    hint: 'Chơi game, giải trí với trò chơi điện tử',
    koreanExample: '퇴근 후에 친구들과 온라인 게임을 해요.',
    vietnameseExample: 'Tôi chơi game trực tuyến với bạn bè sau giờ làm.',
  },
  {
    word: '노래',
    topic: 'Sở thích',
    hint: 'Hát, tạo ra âm nhạc bằng giọng hát',
    koreanExample: '노래방에서 노래 부르기를 좋아해요.',
    vietnameseExample: 'Tôi thích hát ở quán karaoke.',
  },
  {
    word: '캠핑',
    topic: 'Sở thích',
    hint: 'Cắm trại, hoạt động nghỉ ngơi ngoài trời với lều',
    koreanExample: '여름휴가 때 가족과 함께 캠핑을 갔어요.',
    vietnameseExample: 'Tôi đã đi cắm trại cùng gia đình trong kỳ nghỉ hè.',
  },
];

window.allWords = allWords;
